XGH_TIT(`Bookmarks')
XGH_HUL(`2',`Funnies and culture',`dnl
XGH_LIA(`https://www.mindprod.com/jgloss/unmain.html',`unmaintainable code : Java Glossary')
XGH_LIA(`https://github.com/PradyX/unified_kernel_sdm660/commit/f0ee5596b7e4ae1fb8e0f6bf7263cacec559fb76',`fs: block TikTok from launching · PradyX/unified_kernel_sdm660@f0ee559')
XGH_LIA(`https://starwarsintrocreator.kassellabs.io/`#'!/DN75dLHAcDbCzQ-ScoQ1 (o site)',`nem te conto')
XGH_LIA(`https://commandcenter.blogspot.com/2020/01/unix-quiz-answers.html',`command center: Unix Quiz answers')
XGH_LIA(`https://www.jwz.org/doc/censorzilla.html',`CensorZilla')
XGH_LIA(`https://web.archive.org/web/20161118152015/http://ifaq.wap.org/computers/',`Infrequently Asked Questions: Computers')
XGH_LIA(`http://www.ibiblio.org/java/quotes2000.html',`Java Quotes in 2000')
XGH_LIA(`https://www.shlomifish.org/humour/by-others/funroll-loops/Gentoo-is-Rice.html',`Welcome to Gentoo is Rice, the Volume goes to 11 here.')
XGH_LIA(`http://www.cypherspace.org/adam/shirt/',`perl RSA "munitions" T-Shirt homepage')
XGH_LIA(`https://lore.kernel.org/ksummit/CAHk-=wiB6FJknDC5PMfpkg4gZrbSuC3d391VyReM4Wb0+JYXXA@mail.gmail.com/',`Re: Maintainers / Kernel Summit 2021 planning kick-off - Linus Torvalds')
XGH_LIA(`https://www.unicode.org/L2/L2018/18122-mate-emoji.pdf',`18122-mate-emoji.pdf')
XGH_LIA(`http://www.lenna.org/',`The Rest of the Lenna Story')
XGH_LIA(`https://web.archive.org/web/20010413235350/http://www.microsoft.com/NTServer/nts/news/msnw/linuxmyths.asp',`Linux Myths : [Microsoft Windows NT Server 4.0, Linux myths, Windows NT vs Linux, compared with Linux]')
XGH_LIA(`https://home.treasury.gov/policy-issues/financial-sanctions/sanctions-programs-and-country-information',`Sanctions Programs and Country Information | U.S. Department of the Treasury')
')
