XGH_TIT(`Bookmarks')
XGH_UL(`dnl
XGH_LIA(`https://validator.w3.org/',`The W3C Markup Validation Service')
XGH_LIA(`https://www.mathe-fa.de/pt/',`Plotador Matemático MAFA')
')
XGH_UL(`dnl
XGH_LIA(`https://bbs.archlinux.org/index.php',`Arch Linux Forums')
XGH_LIA(`https://www.newgrounds.com/',`Newgrounds.com — Everything, By Everyone')
')
XGH_UL(`XGH_LIA(`https://www.ufsm.br/pet/ciencia-da-computacao/',`PET Ciência da Computação – Programa de Educação Tutorial')')
XGH_UL(`XGH_LIA(`http://www-usr.inf.ufsm.br/~benhur/l12020a/',`ELC1065 - Laboratório de Programação I - UFSM')')
XGH_UL(`XGH_LIA(`https://github.com/EbookFoundation/free-programming-books',`free-programming-books')')
XGH_UL(`dnl
XGH_LIA(`https://github.com/codeplea/genann',`GitHub - codeplea/genann: simple neural network library in ANSI C')
XGH_LIA(`http://leenissen.dk/fann/wp/',`Fast Artificial Neural Network Library (FANN)')
XGH_LIA(`http://lwneuralnet.sourceforge.net/',`Lightweight Neural Network')
')
XGH_UL(`dnl
XGH_LIA(`https://www.tablesgenerator.com/',`Create LaTeX tables online – TablesGenerator.com')
XGH_LIA(`https://sourcehut.org/',`sourcehut - the hacker@aq@s forge')
XGH_LIA(`https://www.overleaf.com/',`Overleaf, Online LaTeX Editor')
XGH_LIA(`https://www.rsync.net/index.html',`rsync - Cloud Storage for Offsite Backup')
XGH_LIA(`https://www.flickr.com/',`Flickr')
')
XGH_UL(`dnl
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc4646',`RFC4646 Tags for Identifying Languages')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc8446',`RFC8446 The Transport Layer Security (TLS) Protocol Version 1.3')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc5246',`RFC5246 The Transport Layer Security (TLS) Protocol Version 1.2')
XGH_LIA(`gemini://gemini.circumlunar.space/docs/specification.gmi',`Project Gemini Speculative specification')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc2616',`RFC2616 Hypertext Transfer Protocol -- HTTP/1.1')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc3875',`RFC3875 The Common Gateway Interface (CGI) Version 1.1')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc3986',`RFC3986 Uniform Resource Identifier (URI): Generic Syntax')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc2046',`Multipurpose Internet Mail Extensions (MIME) Part Two: Media Types')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc1436',`RFC1436 The Internet Gopher Protocol')
XGH_LIA(`https://datatracker.ietf.org/doc/html/rfc7540',`RFC7540 Hypertext Transfer Protocol Version 2 (HTTP/2)')
')
XGH_UL(`dnl
XGH_LIA(`https://www.memorymanagement.org/',`Home — Memory Management Reference 4.0 documentation')
XGH_LIA(`https://github.com/mxgmn',`mxgmn (Maxim Gumin)')
XGH_LIA(`https://downloads.haskell.org/~ghc/latest/docs/html/libraries/',`Haskell Hierarchical Libraries')
XGH_LIA(`https://nlpprogress.com/',`Tracking Progress in Natural Language Processing | NLP-progress')
XGH_LIA(`https://tldp.org/',`The Linux Documentation Project')
XGH_LIA(`https://www.funtoo.org/Category:Articles',`Category:Articles - Funtoo')
XGH_LIA(`https://thebookofshaders.com/',`The Book of Shaders')
XGH_LIA(`https://tldp.org/HOWTO/Software-Release-Practice-HOWTO/patching.html',`Good patching practice')
XGH_LIA(`http://www.kegel.com/academy/opensource.html',`Contributing to Open Source Projects HOWTO')
XGH_LIA(`https://tomassetti.me/antlr-mega-tutorial/',`The ANTLR Mega Tutorial')
XGH_LIA(`https://stackoverflow.com/questions/1878974/redefine-tab-as-4-spaces',`vim - Redefine tab as 4 spaces - Stack Overflow')
XGH_LIA(`https://en.wikipedia.org/wiki/Wikipedia:Language_recognition_chart',`Wikipedia:Language recognition chart - Wikipedia')
XGH_LIA(`https://tomassetti.me/resources-create-programming-languages/',`68 Resources on creating programming languages')
XGH_LIA(`http://book.realworldhaskell.org/read/',`Real World Haskell')
XGH_LIA(`https://bitcoinbook.info/',`Mastering Bitcoin – The Bitcoin Book – Programming the Open Blockchain')
XGH_LIA(`https://news.ycombinator.com/item?id=11070797',`Ask HN: What do you use to manage dotfiles? | Hacker News')
XGH_LIA(`https://stackoverflow.com/questions/65820/unit-testing-c-code',`Unit Testing C Code - Stack Overflow')
XGH_LIA(`https://wiki.hydrogenaud.io/index.php?title=Topic_Index',`Topic Index - Hydrogenaudio Knowledgebase')
XGH_LIA(`https://www.in-ulm.de/~mascheck/various/uuoc/',`Useful use of cat(1)')
XGH_LIA(`https://4chan-science.fandom.com/wiki/Mathematics',`Mathematics | /sci/ Wiki | Fandom')
XGH_LIA(`https://sanctum.geek.nz/arabesque/actually-using-ed/',`Actually using ed | Arabesque')
XGH_LIA(`https://wiki.osdev.org/Main_Page',`Expanded Main Page - OSDev Wiki')
XGH_LIA(`https://www.learncpp.com/',`Learn C++')
XGH_LIA(`https://lazyfoo.net/tutorials/OpenGL/index.php',`Lazy Foo@aq@ Productions - OpenGL Tutorials')
XGH_LIA(`https://lazyfoo.net/tutorials/SDL/',`Lazy Foo@aq@ Productions - Beginning Game Programming v2.0')
XGH_LIA(`https://bbs.archlinux.org/viewtopic.php?id=161740',`A Noobs Quest to Understanding dwm [and window managers in general] / Newbie Corner / Arch Linux Forums')
XGH_LIA(`https://www.cl.cam.ac.uk/~mgk25/unicode.html',`UTF-8 and Unicode FAQ')
XGH_LIA(`https://www.agner.org/optimize/',`Software optimization resources. C++ and assembly. Windows, Linux, BSD, Mac OS X')
XGH_LIA(`https://stackoverflow.com/questions/91791/grep-and-sed-equivalent-for-xml-command-line-processing',`Grep and Sed Equivalent for XML Command Line Processing - Stack Overflow')
XGH_LIA(`https://wiki.creativecommons.org/wiki/Main_Page',`Creative Commons')
XGH_LIA(`http://utf8everywhere.org/',`UTF-8 Everywhere')
XGH_LIA(`https://www.youtube.com/c/FastbitEmbeddedBrainAcademy/videos',`Fastbit Embedded Brain Academy - YouTube')
')
XGH_UL(`dnl
XGH_LIA(`https://css-tricks.com/snippets/css/a-guide-to-flexbox/',`A Complete Guide to Flexbox | CSS-Tricks')
XGH_LIA(`https://css-tricks.com/snippets/css/complete-guide-grid',`A Complete Guide to Grid | CSS-Tricks')
')
XGH_UL(`dnl
XGH_LIA(`https://www.youtube.com/playlist?list=PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6',`Blender Fundamentals 2.8')
XGH_LIA(`https://cgsociety.org/',`CGSociety')
XGH_LIA(`https://blenderartists.org/',`Blender Artists Community')
')
XGH_UL(`dnl
XGH_LIA(`https://github.com/xyproto/battlestar',`xyproto/battlestar: A different take on Assembly')
XGH_LIA(`https://www.ollydbg.de/',`OllyDbg v1.10')
XGH_LIA(`https://github.com/runestubbe/Crinkler',`runestubbe/Crinkler: Crinkler is an executable file compressor')
XGH_LIA(`https://rada.re/n/radare2.html',`radare2')
XGH_LIA(`https://github.com/djpohly/dwl',`djpohly/dwl: dwm for Wayland')
XGH_LIA(`https://github.com/ventoy/Ventoy',`ventoy/Ventoy: A new bootable USB solution.')
XGH_LIA(`https://github.com/facebookincubator/BOLT',`facebookincubator/BOLT: Binary Optimization and Layout Tool')
XGH_LIA(`https://beyondgrep.com/more-tools/',`More tools for searching source code')
XGH_LIA(`https://www.w3.org/Tools/',`Tools for WWW providers')
XGH_LIA(`http://www.fmwconcepts.com/imagemagick/index.php',`Fred@aq@s ImageMagick Scripts')
XGH_LIA(`https://www.schaffter.ca/mom/momdoc/definitions.html',`Mom -- Definitions and Terms')
XGH_LIA(`http://www.faqs.org/faqs/text-faq/',`comp.text Frequently Asked Questions')
XGH_LIA(`https://git-scm.com/book/en/v2',`Git Pro Book')
XGH_LIA(`https://learnbchs.org/',`BCHS: BSD, C, httpd, SQLite')
XGH_LIA(`https://www.eiffel.com/',`Home | Eiffel Software - The Home of EiffelStudio')
XGH_LIA(`https://wiki.postmarketos.org/wiki/Motorola_Moto_G4_Play_(motorola-harpia)',`Motorola Moto G4 Play (motorola-harpia) - postmarketOS')
XGH_LIA(`http://lilypond.org/',`LilyPond – Music notation for everyone')
XGH_LIA(`https://ptolemy.berkeley.edu/projects/embedded/pubs/downloads/',`Embedded Downloads')
XGH_LIA(`https://gbatemp.net/threads/medicat-usb-a-multiboot-linux-usb-for-pc-repair.361577/',`MediCat USB - A Multiboot Linux USB for PC Repair')
XGH_LIA(`https://suckless.org/rocks/',`software that sucks less')
XGH_LIA(`https://github.com/borgbackup/borg',`GitHub - borgbackup/borg')
XGH_LIA(`https://vfxforth.com/',`: VFX forth ;')
XGH_LIA(`https://web.archive.org/web/20180711192755/http://mirror.corenoc.de/digitalrivercontent.net/',`Microsoft DigitalRiver Mirror')
XGH_LIA(`https://cr.yp.to/qhasm.html',`qhasm: tools to help write high-speed software')
XGH_LIA(`http://www.brendangregg.com/perf.html',`Linux perf Examples')
XGH_LIA(`https://github.com/antlr/grammars-v4/',`antlr/grammars-v4: Grammars written for ANTLR v4')
XGH_LIA(`https://github.com/google/re2',`google/re2')
')
XGH_UL(`dnl
XGH_LIA(`http://www.inf.puc-rio.br/~roberto/lpeg/',`LPeg - Parsing Expression Grammars For Lua')
XGH_LIA(`https://tdop.github.io/',`TDOP Pratt')
XGH_LIA(`http://crockford.com/javascript/tdop/tdop.html',`Top Down Operator Precedence')
XGH_LIA(`https://pdos.csail.mit.edu/~baford/packrat/thesis/',`Packrat Parsing: a Practical Linear-Time Algorithm with Backtracking')
XGH_LIA(`https://www.piumarta.com/software/peg/',`peg/leg')
XGH_LIA(`https://www.colm.net/open-source/ragel/',`Ragel State Machine Compiler')
')
XGH_UL(`dnl
XGH_LIA(`https://www.youtube.com/channel/UClT57Bq5io_kABtihe67C7w/videos',`All Electronics - YouTube')
XGH_LIA(`https://www.4004.com/',`4004')
XGH_LIA(`https://www.j-core.org/',`J-core')
XGH_LIA(`http://www.apollo-core.com/',`APOLLO 68080')
XGH_LIA(`http://nandgame.com/',`NandGame - Build a computer from scratch')
XGH_LIA(`https://eater.net/',`Ben Eater')
XGH_LIA(`https://github.com/riscv-boom/riscv-boom',`riscv-boom/riscv-boom: SonicBOOM: The Berkeley Out-of-Order Machine')
')
XGH_UL(`dnl
XGH_LIA(`https://parahumans.wordpress.com/',`Worm | A Complete Web Serial')
XGH_LIA(`http://www.cypherspace.org/adam/shirt/',`perl RSA "munitions" T-Shirt homepage')
XGH_LIA(`https://0.30000000000000004.com/',`Floating Point Math')
XGH_LIA(`https://lore.kernel.org/ksummit/CAHk-=wiB6FJknDC5PMfpkg4gZrbSuC3d391VyReM4Wb0+JYXXA@mail.gmail.com/',`Re: Maintainers / Kernel Summit 2021 planning kick-off - Linus Torvalds')
XGH_LIA(`https://www.unicode.org/L2/L2018/18122-mate-emoji.pdf',`18122-mate-emoji.pdf')
XGH_LIA(`http://www.lenna.org/',`The Rest of the Lenna Story')
XGH_LIA(`https://web.archive.org/web/20010413235350/http://www.microsoft.com/NTServer/nts/news/msnw/linuxmyths.asp',`Linux Myths : [Microsoft Windows NT Server 4.0, Linux myths, Windows NT vs Linux, compared with Linux]')
XGH_LIA(`https://www.funtoo.org/Bash_by_Example,_Part_3',`Bash by Example, Part 3 - Funtoo')
XGH_LIA(`https://www.youtube.com/user/TheWickedNorth/videos?view=0&sort=p&flow=grid',`TheWickedNorth - YouTube')
XGH_LIA(`https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/',`As We May Think - The Atlantic')
XGH_LIA(`https://www.jwz.org/doc/censorzilla.html',`CensorZilla')
XGH_LIA(`http://home.mcom.com/people/paquin/',`Temple @aq@O@aq@ Pacman')
XGH_LIA(`https://www.jwz.org/webcollage/',`WebCollage: Exterminate All Rational Thought')
XGH_LIA(`https://github.com/PradyX/unified_kernel_sdm660/commit/f0ee5596b7e4ae1fb8e0f6bf7263cacec559fb76',`fs: block TikTok from launching · PradyX/unified_kernel_sdm660@f0ee559')
XGH_LIA(`http://www.art.net/',`Art.Net (also known as "Art on the Net")')
XGH_LIA(`https://www.mindprod.com/jgloss/unmain.html',`unmaintainable code : Java Glossary')
XGH_LIA(`https://youtu.be/3RFun58Gt7A',`Midwest FurFest - YouTube')
XGH_LIA(`https://www.youtube.com/watch?v=PGqCeSjNuTY',`Anton: A Special-Purpose Machine That Achieves a Hundred-Fold Speedup in Biomolecular Simulations - YouTube')
XGH_LIA(`http://bastiat.org/en/twisatwins.html',`That Which is Seen, and That Which is Not Seen; by Frederic Bastiat')
XGH_LIA(`https://predictionbook.com/',`PredictionBook: How sure are you?')
XGH_LIA(`https://commandcenter.blogspot.com/2020/01/unix-quiz-answers.html',`command center: Unix Quiz answers')
XGH_LIA(`https://web.archive.org/web/20161118152015/http://ifaq.wap.org/computers/',`Infrequently Asked Questions: Computers')
XGH_LIA(`http://fare.tunes.org/LispM.html',`A few things I know about LISP Machines')
XGH_LIA(`https://web.archive.org/web/20151208143727/https://github.com/opal/opal/issues/941',`Transphobic maintainer should be removed from project · Issue `#'941 · opal/opal · GitHub')
XGH_LIA(`https://web.archive.org/web/20151210081611/https://github.com/opal/opal/issues/942',`Create a Code of Conduct · Issue `#'942 · opal/opal · GitHub')
XGH_LIA(`https://llk.media.mit.edu/courses/readings/scratch-proposal-v2.pdf',`Microsoft Word - proposal-handout v2.doc')
XGH_LIA(`https://dwheeler.com/essays/apple-goto-fail.html',`The Apple goto fail vulnerability: lessons learned')
XGH_LIA(`https://www.shlomifish.org/humour/by-others/funroll-loops/Gentoo-is-Rice.html',`Welcome to Gentoo is Rice, the Volume goes to 11 here.')
XGH_LIA(`http://www.ibiblio.org/java/quotes2000.html',`Java Quotes in 2000')
XGH_LIA(`https://research.swtch.com/version-sat',`research!rsc: Version SAT')
XGH_LIA(`https://michael.stapelberg.ch/posts/2019-08-17-linux-package-managers-are-slow/',`Linux package managers are slow (2019) - Michael Stapelberg')
XGH_LIA(`https://bitcointalk.org/index.php?topic=375643.0',`I AM HODLING')
XGH_LIA(`https://joshdata.me/iceberger.html',`Iceberger')
XGH_LIA(`http://subgenius.com/pam1/pamphlet_p1.html',`Pamphlet `#'1 - page 1')
XGH_LIA(`https://www.jwz.org/dadadodo/',`DadaDodo')
')
XGH_UL(`dnl
XGH_LIA(`https://research.swtch.com/',`research!rsc')
XGH_LIA(`https://www.internalpointers.com/',`Internal Pointers - Internal Pointers')
XGH_LIA(`http://lambda-the-ultimate.org/',`Lambda the Ultimate | Programming Languages Weblog')
XGH_LIA(`https://cellperformance.beyond3d.com/articles/index.html',`CellPerformance')
XGH_LIA(`https://fabiensanglard.net/',`Fabien Sanglard@aq@s Website')
XGH_LIA(`https://sanctum.geek.nz/arabesque/',`Arabesque | Systems, Tools, and Terminal Science')
XGH_LIA(`luna.phonk.net',`Welcome to Phonk.net')
XGH_LIA(`https://fexpr.blogspot.com/',`Structural insight')
XGH_LIA(`https://tomassetti.me/',`Our articles - Strumenta')
')
XGH_UL(`dnl
XGH_LIA(`https://www.codecogs.com/latex/eqneditor.php?lang=pt-br',`Editor Online de Equações LaTeX - crie, integre e baixe')
XGH_LIA(`https://code.google.com/archive/p/mdtufsm-ppgi/source/default/source',`Google Code Archive - Long-term storage for Google Code Project Hosting.')
XGH_LIA(`https://www.sbc.org.br/documentos-da-sbc/category/169-templates-para-artigos-e-ca%20pitulos-de-livros',`Templates para Artigos e Capitulos de Livros')
XGH_LIA(`https://www.edx.org/',`edX')
XGH_LIA(`https://pt.coursera.org/',`Coursera')
XGH_LIA(`https://www.ufsm.br/orgaos-suplementares/biblioteca/',`Bibliotecas UFSM')
XGH_LIA(`https://www.elsevier.com/books-and-journals',`Elsevier')
XGH_LIA(`https://www.acm.org/',`Association for Computing Machinery')
XGH_LIA(`https://ieeexplore.ieee.org/Xplore/home.jsp',`IEEE Xplore')
XGH_LIA(`https://www.ufsm.br/orgaos-executivos/agittec',`AGITTEC – Agência de Inovação e Transferência de Tecnologia')
XGH_LIA(`https://www.orbit.com/',`Orbit')
XGH_LIA(`https://www.epo.org/searching-for-patents.html',`EPO')
XGH_LIA(`https://www.uspto.gov/',`United States Patent and Trademark Office')
XGH_LIA(`https://www.gov.br/inpi/pt-br',`Instituto Nacional de Propriedade Industrial')
')
XGH_UL(`dnl
XGH_LIA(`http://www.wheaty.net/',`Wheaty Productions Inc.')
XGH_LIA(`https://lcamtuf.coredump.cx/',`[lcamtuf.coredump.cx]')
XGH_LIA(`http://jon-jacky.github.io/home/links.html',`Interesting web sites')
XGH_LIA(`http://www.etalabs.net/',`Eta Labs')
XGH_LIA(`http://filter24.org/',`.filter24 : music + technology from rob buse')
XGH_LIA(`https://open.spotify.com/playlist/0wbWiD8bxhhSFMLyNx8Mf8?si=WOwM4zGnQQmdFHTXNfl12g',`Japanese Vibes - Spotify')
XGH_LIA(`https://prodesigntools.com/',`ProDesignTools - Helping Adobe<sup>&reg;</sup> Users since 2009')
XGH_LIA(`https://www.shlomifish.org/',`Shlomi Fish’s Homepage')
XGH_LIA(`https://home.treasury.gov/policy-issues/financial-sanctions/sanctions-programs-and-country-information',`Sanctions Programs and Country Information | U.S. Department of the Treasury')
XGH_LIA(`https://isynchronise.com/',`isynchronise – the home of synchronic computation')
XGH_LIA(`http://www.kegel.com/',`Dan Kegel@aq@s Web Hostel')
')
XGH_UL(`dnl
XGH_LIA(`https://challenges.ethereum.org/',`Ethereum Bounties')
XGH_LIA(`https://en.wikipedia.org/wiki/ICFP_Programming_Contest',`ICFP Programming Contest - Wikipedia')
')
XGH_UL(`dnl
XGH_LIA(`https://pbrisbin.com/',`pbrisbin dot com')
XGH_LIA(`https://eli.thegreenplace.net/',`Eli Bendersky@aq@s website')
')
XGH_UL(`dnl
XGH_LIA(`https://www.newgrounds.com/search/conduct/audio?sort=views-desc&user=Rukkus',`Rukkus I love you where are you')
XGH_LIA(`https://www.youtube.com/user/TheWickedNorth',`TheWickedNorth - YouTube')
XGH_LIA(`https://www.youtube.com/user/neuIlaryRheinKlange',`neuIlaryRheinKlange - YouTube')
XGH_LIA(`https://www.youtube.com/user/IlaryRhineKlange/featured',`IlaryRhineKlange - YouTube')
XGH_LIA(`https://www.youtube.com/user/avrilfan2213',`avrilfan2213 - YouTube')
')
