SECTION_X(1, "Utility",
	LINK_X("http://localhost:8384"      , "Sync"                                            )
	LINK_X("http://localhost:7396"      , "Folding@home"                                    )
	LINK_X("https://validator.w3.org/"  , "The W3C Markup Validation Service"               )
	LINK_X("https://www.zamzar.com/"    , "Zamzar"                                          )
	LINK_X("http://gen.lib.rus.ec/"     , "Library Genesis<sup>2M</sup>"                    )
	LINK_X("https://www.mathe-fa.de/pt/", "Plotador Matemático MAFA"                        )
	LINK_X("https://lelivros.love/"     , "Le Livros"                                       )
	LINK_X("https://sci-hub.st/"        , "Sci-Hub: removing barriers in the way of science")
)

SECTION_X(1, "Places",
	LINK_X("https://discord.com/app"            , "Discord"          )
	LINK_X("https://web.whatsapp.com/"          , "WhatsApp Web"     )
	LINK_X("https://bbs.archlinux.org/index.php", "Arch Linux Forums")
	LINK_X("https://www.newgrounds.com/"        , "Newgrounds.com — Everything, By Everyone")
)

SECTION_X(1, "UFSM",
	LINK_X("https://www.ufsm.br/pet/ciencia-da-computacao/", "PET Ciência da Computação – Programa de Educação Tutorial")
)
SECTION_X(2, "Disciplinas",
	LINK_X("http://www-usr.inf.ufsm.br/~benhur/l12020a/", "ELC1065 - Laboratório de Programação I - UFSM")
)

SECTION_X(1, "C stuff", NIL)
SECTION_X(2, "Resources",
	LINK_X("https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html"                                , "What Every Computer Scientist Should Know About Floating-Point Arithmetic"                          )
	LINK_X("http://www.ganssle.com/"                                                                        , "The Ganssle Group"                                                                                  )
	LINK_X("http://beefchunk.com/documentation/lang/c/pre-defined-c/precomp.html"                           , "Pre-defined C/C++ Compiler Macros"                                                                  )
	LINK_X("http://locklessinc.com/articles/pthreads_on_windows/"                                           , "Pthreads on Microsoft Windows"                                                                      )
	LINK_X("https://computing.llnl.gov/tutorials/linux_clusters/gpu/NVIDIA.Introduction_to_CUDA_C.1.pdf"    , "Slide 1 - NVIDIA.Introduction_to_CUDA_C.1.pdf"                                                      )
	LINK_X("https://computing.llnl.gov/tutorials/mpi/"                                                      , "Message Passing Interface (MPI)"                                                                    )
	LINK_X("https://computing.llnl.gov/tutorials/parallel_comp/"                                            , "Introduction to Parallel Computing"                                                                 )
	LINK_X("https://computing.llnl.gov/tutorials/pthreads/"                                                 , "POSIX Threads Programming"                                                                          )
	LINK_X("https://stackoverflow.com/questions/1674032/static-const-vs-define-vs-enum"                     , "c - \"static const\" vs \"#define\" vs \"enum\" - Stack Overflow"                                   )
	LINK_X("https://wiki.installgentoo.com/wiki/Programming_resources"                                      , "Programming resources - InstallGentoo Wiki"                                                         )
	LINK_X("http://iso-9899.info/wiki/Books"                                                                , "Books - C"                                                                                          )
	LINK_X("https://gist.github.com/zneak/5ccbe684e6e56a7df8815c3486568f01"                                 , "Quirks of C"                                                                                        )
	LINK_X("https://cses.fi/book/book.pdf"                                                                  , "book.pdf"                                                                                           )
	LINK_X("https://www.gafferongames.com/"                                                                 , "Gaffer On Games"                                                                                    )
	LINK_X("https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md", "free-programming-books/free-programming-books.md at master · EbookFoundation/free-programming-books")
	LINK_X("http://www.cs.gordon.edu/courses/cs320/handouts/C_C++_Syntax_vs_Pascal.html"                    , "A Comparison of the Syntax of C/C++ and Pascal"                                                     )
	LINK_X("https://www.kernel.org/doc/html/latest/process/coding-style.html#typedefs"                      , "Linux kernel coding style — The Linux Kernel documentation"                                         )
	LINK_X("https://github.com/kozross/awesome-c"                                                           , "Awesome C"                                                                                          )
	LINK_X("https://old.reddit.com/r/C_Programming/"                                                        , "C subreddit"                                                                                        )
	LINK_X("https://matt.sh/howto-c"                                                                        , "How to C (as of 2016)"                                                                              )
	LINK_X("http://sekrit.de/webdocs/c/beginners-guide-away-from-scanf.html"                                , "A beginners' guide <i>away</i> from scanf()"                                                        )
	LINK_X("https://computing.llnl.gov/tutorials/openMP/"                                                   , "OpenMP"                                                                                             )
	LINK_X("https://cellperformance.beyond3d.com/articles/2006/06/understanding-strict-aliasing.html"       , "Understanding Strict Aliasing - CellPerformance"                                                    )
	LINK_X("https://cellperformance.beyond3d.com/articles/2006/05/demystifying-the-restrict-keyword.html"   , "Demystifying The Restrict Keyword - CellPerformance"                                                )
	LINK_X("http://poormansprofiler.org/"                                                                   , "poor man's profiler"                                                                                )
	LINK_X("https://www.lysator.liu.se/c/restrict.html"                                                     , "Restricted Pointers in C (Draft 2), X3J11.1 93-006"                                                 )
	LINK_X("https://www.cis.upenn.edu/~lee/06cse480/data/cstyle.ms.pdf"                                     , "cstyle.ms.pdf"                                                                                      )
	LINK_X("https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/rzarg/static_array_index.htm"       , "Static array indices in function parameter declarations (C only)"                                   )
	LINK_X("http://www.brendangregg.com/books.html"                                                         , "Books - Brendan Gregg"                                                                              )
	LINK_X("https://graphics.stanford.edu/~seander/bithacks.html"                                           , "Bit Twiddling Hacks"                                                                                )
	LINK_X("https://wiki.sei.cmu.edu/confluence/display/c/SEI+CERT+C+Coding+Standard"                       , "SEI CERT C Coding Standard - SEI CERT C Coding Standard - Confluence"                               )
	LINK_X("https://nginx.org/en/docs/dev/development_guide.html#code_style"                                , "Development guide#coding_style"                                                                     )
)
SECTION_X(2, "Libraries",
	LINK_X("https://github.com/orangeduck/mpc"                                        , "orangeduck/mpc: A Parser Combinator library for C"                                                       )
	LINK_X("https://github.com/orangeduck/Corange"                                    , "orangeduck/Corange: Pure C Game Engine"                                                                  )
	LINK_X("https://www.hboehm.info/gc/"                                              , "A garbage collector for C and C++"                                                                       )
	LINK_X("https://frankforce.com/frank-engine/"                                     , "The Frank Engine | Killed By A Pixel"                                                                    )
	LINK_X("http://www.leonerd.org.uk/code/libtickit/"                                , "libtickit"                                                                                               )
	LINK_X("https://libuv.org/"                                                       , "libuv | Cross-platform asynchronous I/O"                                                                 )
	LINK_X("https://github.com/Immediate-Mode-UI/Nuklear"                             , "Immediate-Mode-UI/Nuklear: A single-header ANSI C immediate mode cross-platform GUI library"             )
	LINK_X("https://github.com/nothings/single_file_libs"                             , "List of single-file C/C++ libraries"                                                                     )
	LINK_X("https://www.raylib.com/"                                                  , "raylib"                                                                                                  )
	LINK_X("https://github.com/wmcbrine/PDCurses"                                     , "wmcbrine/PDCurses: PDCurses - a curses library for environments tht don't fit the termcap/terminfo model")
	LINK_X("http://www.nongnu.org/avr-libc/"                                          , "AVR Libc Home Page"                                                                                      )
	LINK_X("https://en.cppreference.com/w/c/links/libs"                               , "open source C libraries"                                                                                 )
	LINK_X("https://en.wikipedia.org/wiki/Category:C_(programming_language)_libraries", "Category:C (programming language) libraries - Wikipedia"                                                 )
	LINK_X("https://www.tapirgames.com/blog/open-source-physics-engines"              , "Full List Of Open Source Physics Engines * Blog"                                                         )
)
SECTION_X(3, "Neural Networks",
	LINK_X("https://github.com/codeplea/genann" , "GitHub - codeplea/genann: simple neural network library in ANSI C")
	LINK_X("http://leenissen.dk/fann/wp/"       , "Fast Artificial Neural Network Library (FANN)"                    )
	LINK_X("http://lwneuralnet.sourceforge.net/", "Lightweight Neural Network"                                       )
)
SECTION_X(2, "Projects",
	LINK_X("git://leontynka.twibright.com/links.git", "links Git repository")
)

SECTION_X(1, "Services",
	LINK_X("https://www.tablesgenerator.com/", "Create LaTeX tables online – TablesGenerator.com")
	LINK_X("https://sourcehut.org/"          , "sourcehut - the hacker's forge"                  )
	LINK_X("https://www.overleaf.com/"       , "Overleaf, Online LaTeX Editor"                   )
	LINK_X("https://www.rsync.net/index.html", "rsync - Cloud Storage for Offsite Backup"        )
	LINK_X("https://www.flickr.com/"         , "Flickr"                                          )
	LINK_X("https://lelivros.love/"          , "Le Livros"                                       )
)

SECTION_X(1, "Guides",
	LINK_X("https://www.memorymanagement.org/"                                                                , "Home — Memory Management Reference 4.0 documentation"                                                   )
	LINK_X("https://github.com/mxgmn"                                                                         , "mxgmn (Maxim Gumin)"                                                                                    )
	LINK_X("https://downloads.haskell.org/~ghc/latest/docs/html/libraries/"                                   , "Haskell Hierarchical Libraries"                                                                         )
	LINK_X("https://nlpprogress.com/"                                                                         , "Tracking Progress in Natural Language Processing | NLP-progress"                                        )
	LINK_X("https://tldp.org/"                                                                                , "The Linux Documentation Project"                                                                        )
	LINK_X("https://www.funtoo.org/Category:Articles"                                                         , "Category:Articles - Funtoo"                                                                             )
	LINK_X("https://thebookofshaders.com/"                                                                    , "The Book of Shaders"                                                                                    )
	LINK_X("https://tldp.org/HOWTO/Software-Release-Practice-HOWTO/patching.html"                             , "Good patching practice"                                                                                 )
	LINK_X("http://www.kegel.com/academy/opensource.html"                                                     , "Contributing to Open Source Projects HOWTO"                                                             )
	LINK_X("https://tomassetti.me/antlr-mega-tutorial/"                                                       , "The ANTLR Mega Tutorial"                                                                                )
	LINK_X("https://stackoverflow.com/questions/1878974/redefine-tab-as-4-spaces"                             , "vim - Redefine tab as 4 spaces - Stack Overflow"                                                        )
	LINK_X("https://en.wikipedia.org/wiki/Wikipedia:Language_recognition_chart"                               , "Wikipedia:Language recognition chart - Wikipedia"                                                       )
	LINK_X("https://tomassetti.me/resources-create-programming-languages/"                                    , "68 Resources on creating programming languages"                                                         )
	LINK_X("http://book.realworldhaskell.org/read/"                                                           , "Real World Haskell"                                                                                     )
	LINK_X("https://bitcoinbook.info/"                                                                        , "Mastering Bitcoin – The Bitcoin Book – Programming the Open Blockchain"                                 )
	LINK_X("https://news.ycombinator.com/item?id=11070797"                                                    , "Ask HN: What do you use to manage dotfiles? | Hacker News"                                              )
	LINK_X("https://stackoverflow.com/questions/65820/unit-testing-c-code"                                    , "Unit Testing C Code - Stack Overflow"                                                                   )
	LINK_X("https://wiki.hydrogenaud.io/index.php?title=Topic_Index"                                          , "Topic Index - Hydrogenaudio Knowledgebase"                                                              )
	LINK_X("https://www.in-ulm.de/~mascheck/various/uuoc/"                                                    , "Useful use of cat(1)"                                                                                   )
	LINK_X("https://4chan-science.fandom.com/wiki/Mathematics"                                                , "Mathematics | /sci/ Wiki | Fandom"                                                                      )
	LINK_X("https://sanctum.geek.nz/arabesque/actually-using-ed/"                                             , "Actually using ed | Arabesque"                                                                          )
	LINK_X("https://wiki.osdev.org/Main_Page"                                                                 , "Expanded Main Page - OSDev Wiki"                                                                        )
	LINK_X("https://www.learncpp.com/"                                                                        , "Learn C++"                                                                                              )
	LINK_X("https://lazyfoo.net/tutorials/OpenGL/index.php"                                                   , "Lazy Foo' Productions - OpenGL Tutorials"                                                               )
	LINK_X("https://lazyfoo.net/tutorials/SDL/"                                                               , "Lazy Foo' Productions - Beginning Game Programming v2.0"                                                )
	LINK_X("https://bbs.archlinux.org/viewtopic.php?id=161740"                                                , "A Noobs Quest to Understanding dwm [and window managers in general] / Newbie Corner / Arch Linux Forums")
	LINK_X("https://www.cl.cam.ac.uk/~mgk25/unicode.html"                                                     , "UTF-8 and Unicode FAQ"                                                                                  )
	LINK_X("https://www.agner.org/optimize/"                                                                  , "Software optimization resources. C++ and assembly. Windows, Linux, BSD, Mac OS X"                       )
	LINK_X("https://stackoverflow.com/questions/91791/grep-and-sed-equivalent-for-xml-command-line-processing", "Grep and Sed Equivalent for XML Command Line Processing - Stack Overflow"                               )
	LINK_X("https://wiki.creativecommons.org/wiki/Main_Page"                                                  , "Creative Commons"                                                                                       )
	LINK_X("http://utf8everywhere.org/"                                                                       , "UTF-8 Everywhere"                                                                                       )
)
SECTION_X(2, "Minetest",
	LINK_X("https://your-land.de/index.php/2020/06/26/modding-sources-as-of-june-2020/", "Modding sources as of June 2020"    )
	LINK_X("https://nathansalapat.com/minetest/modding"                                , "Mod Reviews | Nathan's Website"     )
	LINK_X("https://www.lua.org/manual/5.1/"                                           , "Lua 5.1 Reference Manual - contents")
)
SECTION_X(2, "CSS",
	LINK_X("https://css-tricks.com/snippets/css/a-guide-to-flexbox/", "A Complete Guide to Flexbox | CSS-Tricks")
	LINK_X("https://css-tricks.com/snippets/css/complete-guide-grid", "A Complete Guide to Grid | CSS-Tricks"   )
)

SECTION_X(1, "Blender", NIL)
SECTION_X(2, "Tutorials",
	LINK_X("https://www.youtube.com/playlist?list=PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6", "Blender Fundamentals 2.8")
)
SECTION_X(2, "Communities",
	LINK_X("https://cgsociety.org/"     , "CGSociety"                )
	LINK_X("https://blenderartists.org/", "Blender Artists Community")
)

SECTION_X(1, "Software",
	LINK_X("https://github.com/xyproto/battlestar"                                                       , "xyproto/battlestar: A different take on Assembly"              )
	LINK_X("https://www.ollydbg.de/"                                                                     , "OllyDbg v1.10"                                                 )
	LINK_X("https://github.com/runestubbe/Crinkler"                                                      , "runestubbe/Crinkler: Crinkler is an executable file compressor")
	LINK_X("https://rada.re/n/radare2.html"                                                              , "radare2"                                                       )
	LINK_X("https://github.com/djpohly/dwl"                                                              , "djpohly/dwl: dwm for Wayland"                                  )
	LINK_X("https://github.com/ventoy/Ventoy"                                                            , "ventoy/Ventoy: A new bootable USB solution."                   )
	LINK_X("https://github.com/facebookincubator/BOLT"                                                   , "facebookincubator/BOLT: Binary Optimization and Layout Tool"   )
	LINK_X("https://www.zotero.org/support/start"                                                        , "start [Zotero Documentation]"                                  )
	LINK_X("https://beyondgrep.com/more-tools/"                                                          , "More tools for searching source code"                          )
	LINK_X("https://www.w3.org/Tools/"                                                                   , "Tools for WWW providers"                                       )
	LINK_X("http://www.fmwconcepts.com/imagemagick/index.php"                                            , "Fred's ImageMagick Scripts"                                    )
	LINK_X("https://www.schaffter.ca/mom/momdoc/definitions.html#top"                                    , "Mom -- Definitions and Terms"                                  )
	LINK_X("http://www.faqs.org/faqs/text-faq/"                                                          , "comp.text Frequently Asked Questions"                          )
	LINK_X("https://git-scm.com/book/en/v2"                                                              , "Git Pro Book"                                                  )
 	LINK_X("https://learnbchs.org/"                                                                      , "BCHS: BSD, C, httpd, SQLite"                                   )
	LINK_X("https://www.eiffel.com/"                                                                     , "Home | Eiffel Software - The Home of EiffelStudio"             )
	LINK_X("https://wiki.postmarketos.org/wiki/Motorola_Moto_G4_Play_(motorola-harpia)"                  , "Motorola Moto G4 Play (motorola-harpia) - postmarketOS"        )
	LINK_X("http://lilypond.org/"                                                                        , "LilyPond – Music notation for everyone"                        )
	LINK_X("https://ptolemy.berkeley.edu/projects/embedded/pubs/downloads/"                              , "Embedded Downloads"                                            )
	LINK_X("https://gbatemp.net/threads/medicat-usb-a-multiboot-linux-usb-for-pc-repair.361577/"         , "MediCat USB - A Multiboot Linux USB for PC Repair"             )
	LINK_X("https://suckless.org/rocks/"                                                                 , "software that sucks less"                                      )
	LINK_X("https://github.com/borgbackup/borg"                                                          , "GitHub - borgbackup/borg"                                      )
	LINK_X("https://vfxforth.com/"                                                                       , ": VFX forth ;"                                                 )
	LINK_X("https://web.archive.org/web/20180711192755/http://mirror.corenoc.de/digitalrivercontent.net/", "Microsoft DigitalRiver Mirror"                                 )
	LINK_X("https://tldp.org/"                                                                           , "The Linux Documentation Project"                               )
	LINK_X("https://cr.yp.to/qhasm.html"                                                                 , "qhasm: tools to help write high-speed software"                )
	LINK_X("http://www.brendangregg.com/perf.html"                                                       , "Linux perf Examples"                                           )
	LINK_X("https://github.com/antlr/grammars-v4/"                                                       , "antlr/grammars-v4: Grammars written for ANTLR v4"              )
	LINK_X("https://github.com/google/re2"                                                               , "google/re2"                                                    )
)
SECTION_X(2, "Make",
	LINK_X("https://nullprogram.com/blog/2017/08/20/"                            , "A Tutorial on Portable Makefiles")
	LINK_X("https://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html", "make"                            )
	LINK_X("https://docs.microsoft.com/en-us/cpp/build/reference/nmake-reference", "NMAKE Reference | Microsoft Docs")
)
SECTION_X(2, "Parsers",
	LINK_X("http://www.inf.puc-rio.br/~roberto/lpeg/"          , "LPeg - Parsing Expression Grammars For Lua"                          )
	LINK_X("https://tdop.github.io/"                           , "TDOP Pratt"                                                          )
	LINK_X("http://crockford.com/javascript/tdop/tdop.html"    , "Top Down Operator Precedence"                                        )
	LINK_X("https://pdos.csail.mit.edu/~baford/packrat/thesis/", "Packrat Parsing: a Practical Linear-Time Algorithm with Backtracking")
	LINK_X("https://www.piumarta.com/software/peg/"            , "peg/leg"                                                             )
	LINK_X("https://www.colm.net/open-source/ragel/"           , "Ragel State Machine Compiler"                                        )
)

SECTION_X(1, "Electronics",
	LINK_X("https://www.youtube.com/channel/UClT57Bq5io_kABtihe67C7w/videos", "All Electronics - YouTube"                                               )
	LINK_X("https://www.4004.com/"                                          , "4004"                                                                    )
	LINK_X("https://www.j-core.org/"                                        , "J-core"                                                                  )
	LINK_X("http://www.apollo-core.com/"                                    , "APOLLO 68080"                                                            )
	LINK_X("http://nandgame.com/"                                           , "NandGame - Build a computer from scratch"                                )
	LINK_X("https://eater.net/"                                             , "Ben Eater"                                                               )
	LINK_X("https://github.com/riscv-boom/riscv-boom"                       , "riscv-boom/riscv-boom: SonicBOOM:<br />The Berkeley Out-of-Order Machine")
)

SECTION_X(1, "Culture",
	LINK_X("https://parahumans.wordpress.com/"                                                                        , "Worm | A Complete Web Serial"                                                                               )
	LINK_X("http://www.cypherspace.org/adam/shirt/"                                                                   , "perl RSA \"munitions\" T-Shirt homepage"                                                                    )
	LINK_X("https://0.30000000000000004.com/"                                                                         , "Floating Point Math"                                                                                        )
	LINK_X("https://lore.kernel.org/ksummit/CAHk-=wiB6FJknDC5PMfpkg4gZrbSuC3d391VyReM4Wb0+JYXXA@mail.gmail.com/"      , "Re: Maintainers / Kernel Summit 2021 planning kick-off - Linus Torvalds"                                    )
	LINK_X("https://www.unicode.org/L2/L2018/18122-mate-emoji.pdf"                                                    , "18122-mate-emoji.pdf"                                                                                       )
	LINK_X("https://www.youtube.com/watch?v=6DYJXSSgW08"                                                              , "Brain Wall - Crazy Japanese Gameshow LOL - YouTube"                                                         )
	LINK_X("http://www.lenna.org/"                                                                                    , "The Rest of the Lenna Story"                                                                                )
	LINK_X("https://web.archive.org/web/20010413235350/http://www.microsoft.com/NTServer/nts/news/msnw/linuxmyths.asp", "Linux Myths : [Microsoft Windows NT Server 4.0, Linux myths, Windows NT vs Linux, compared with Linux]"     )
	LINK_X("https://www.funtoo.org/Bash_by_Example,_Part_3"                                                           , "Bash by Example, Part 3 - Funtoo"                                                                           )
	LINK_X("https://www.youtube.com/user/TheWickedNorth/videos?view=0&sort=p&flow=grid"                               , "TheWickedNorth - YouTube"                                                                                   )
	LINK_X("https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/"                             , "As We May Think - The Atlantic"                                                                             )
	LINK_X("https://www.jwz.org/doc/censorzilla.html"                                                                 , "CensorZilla"                                                                                                )
	LINK_X("http://home.mcom.com/people/paquin/"                                                                      , "Temple 'O' Pacman"                                                                                          )
	LINK_X("https://www.jwz.org/webcollage/"                                                                          , "WebCollage: Exterminate All Rational Thought"                                                               )
	LINK_X("https://github.com/PradyX/unified_kernel_sdm660/commit/f0ee5596b7e4ae1fb8e0f6bf7263cacec559fb76"          , "fs: block TikTok from launching · PradyX/unified_kernel_sdm660@f0ee559"                                     )
	LINK_X("http://www.art.net/"                                                                                      , "Art.Net (also known as \"Art on the Net\")"                                                                 )
	LINK_X("https://www.mindprod.com/jgloss/unmain.html"                                                              , "unmaintainable code : Java Glossary"                                                                        )
	LINK_X("https://youtu.be/3RFun58Gt7A"                                                                             , "Midwest FurFest - YouTube"                                                                                  )
	LINK_X("https://www.youtube.com/watch?v=PGqCeSjNuTY"                                                              , "Anton: A Special-Purpose Machine That Achieves a Hundred-Fold Speedup in Biomolecular Simulations - YouTube")
	LINK_X("http://bastiat.org/en/twisatwins.html"                                                                    , "That Which is Seen, and That Which is Not Seen; by Frederic Bastiat"                                        )
	LINK_X("https://predictionbook.com/"                                                                              , "PredictionBook: How sure are you?"                                                                          )
	LINK_X("https://commandcenter.blogspot.com/2020/01/unix-quiz-answers.html"                                        , "command center: Unix Quiz answers"                                                                          )
	LINK_X("https://web.archive.org/web/20161118152015/http://ifaq.wap.org/computers/"                                , "Infrequently Asked Questions: Computers"                                                                    )
	LINK_X("http://fare.tunes.org/LispM.html"                                                                         , "A few things I know about LISP Machines"                                                                    )
	LINK_X("https://web.archive.org/web/20151208143727/https://github.com/opal/opal/issues/941"                       , "Transphobic maintainer should be removed from project · Issue #941 · opal/opal · GitHub"                    )
	LINK_X("https://web.archive.org/web/20151210081611/https://github.com/opal/opal/issues/942"                       , "Create a Code of Conduct · Issue #942 · opal/opal · GitHub"                                                 )
	LINK_X("https://llk.media.mit.edu/courses/readings/scratch-proposal-v2.pdf"                                       , "Microsoft Word - proposal-handout v2.doc"                                                                   )
	LINK_X("https://dwheeler.com/essays/apple-goto-fail.html"                                                         , "The Apple goto fail vulnerability: lessons learned"                                                         )
	LINK_X("https://www.shlomifish.org/humour/by-others/funroll-loops/Gentoo-is-Rice.html"                            , "Welcome to Gentoo is Rice, the Volume goes to 11 here."                                                     )
	LINK_X("http://www.ibiblio.org/java/quotes2000.html"                                                              , "Java Quotes in 2000"                                                                                        )
	LINK_X("https://research.swtch.com/version-sat"                                                                   , "research!rsc: Version SAT"                                                                                  )
	LINK_X("https://michael.stapelberg.ch/posts/2019-08-17-linux-package-managers-are-slow/"                          , "Linux package managers are slow (2019) - Michael Stapelberg"                                                )
	LINK_X("https://bitcointalk.org/index.php?topic=375643.0"                                                         , "I AM HODLING"                                                                                               )
	LINK_X("https://joshdata.me/iceberger.html"                                                                       , "Iceberger"                                                                                                  )
	LINK_X("http://subgenius.com/pam1/pamphlet_p1.html"                                                               , "Pamphlet #1 - page 1"                                                                                       )
	LINK_X("https://www.jwz.org/dadadodo/"                                                                            , "DadaDodo"                                                                                                   )
)

SECTION_X(1, "Blogs",
	LINK_X("https://www.internalpointers.com/"                       , "Internal Pointers - Internal Pointers"             )
	LINK_X("http://lambda-the-ultimate.org/"                         , "Lambda the Ultimate | Programming Languages Weblog")
	LINK_X("https://cellperformance.beyond3d.com/articles/index.html", "CellPerformance"                                   )
	LINK_X("https://fabiensanglard.net/"                             , "Fabien Sanglard's Website"                         )
	LINK_X("https://sanctum.geek.nz/arabesque/"                      , "Arabesque | Systems, Tools, and Terminal Science"  )
	LINK_X("luna.phonk.net"                                          , "Welcome to Phonk.net"                              )
	LINK_X("https://fexpr.blogspot.com/"                             , "Structural insight"                                )
	LINK_X("https://tomassetti.me/"                                  , "Our articles - Strumenta"                          )
)

SECTION_X(1, "Research",
	LINK_X("https://www.codecogs.com/latex/eqneditor.php?lang=pt-br"                                              , "Editor Online de Equações LaTeX - crie, integre e baixe"                 )
	LINK_X("https://code.google.com/archive/p/mdtufsm-ppgi/source/default/source"                                 , "Google Code Archive - Long-term storage for Google Code Project Hosting.")
	LINK_X("https://www.sbc.org.br/documentos-da-sbc/category/169-templates-para-artigos-e-ca%20pitulos-de-livros", "Templates para Artigos e Capitulos de Livros"                            )
	LINK_X("https://www.edx.org/"                                                                                 , "edX"                                                                     )
	LINK_X("https://pt.coursera.org/"                                                                             , "Coursera"                                                                )
	LINK_X("https://www.ufsm.br/orgaos-suplementares/biblioteca/"                                                 , "Bibliotecas UFSM"                                                        )
	LINK_X("https://www.elsevier.com/books-and-journals"                                                          , "Elsevier"                                                                )
	LINK_X("https://www.acm.org/"                                                                                 , "Association for Computing Machinery"                                     )
	LINK_X("https://ieeexplore.ieee.org/Xplore/home.jsp"                                                          , "IEEE Xplore"                                                             )
	LINK_X("https://www.ufsm.br/orgaos-executivos/agittec"                                                        , "AGITTEC – Agência de Inovação e Transferência de Tecnologia"             )
	LINK_X("https://www.orbit.com/"                                                                               , "Orbit"                                                                   )
	LINK_X("https://www.epo.org/searching-for-patents.html"                                                       , "EPO"                                                                     )
	LINK_X("https://www.uspto.gov/"                                                                               , "United States Patent and Trademark Office"                               )
	LINK_X("https://www.gov.br/inpi/pt-br"                                                                        , "Instituto Nacional de Propriedade Industrial"                            )
)

SECTION_X(1, "Other links",
	LINK_X("http://www.wheaty.net/"                                                                                , "Wheaty Productions Inc."                                                     )
	LINK_X("https://lcamtuf.coredump.cx/"                                                                          , "[lcamtuf.coredump.cx]"                                                       )
	LINK_X("http://jon-jacky.github.io/home/links.html"                                                            , "Interesting web sites"                                                       )
	LINK_X("http://www.etalabs.net/"                                                                               , "Eta Labs"                                                                    )
	LINK_X("http://filter24.org/"                                                                                  , ".filter24 : music + technology from rob buse"                                )
	LINK_X("https://open.spotify.com/playlist/0wbWiD8bxhhSFMLyNx8Mf8?si=WOwM4zGnQQmdFHTXNfl12g"                    , "Japanese Vibes - Spotify"                                                    )
	LINK_X("https://prodesigntools.com/"                                                                           , "ProDesignTools - Helping Adobe<sup>&reg;</sup> Users since 2009"             )
	LINK_X("https://www.shlomifish.org/"                                                                           , "Shlomi Fish’s Homepage"                                                      )
	LINK_X("https://home.treasury.gov/policy-issues/financial-sanctions/sanctions-programs-and-country-information", "Sanctions Programs and Country Information | U.S. Department of the Treasury")
	LINK_X("https://isynchronise.com/"                                                                             , "isynchronise – the home of synchronic computation"                           )
	LINK_X("http://www.kegel.com/"                                                                                 , "Dan Kegel's Web Hostel"                                                      )
)

SECTION_X(1, "Bounties and contests",
	LINK_X("https://challenges.ethereum.org/"                      , "Ethereum Bounties"                   )
	LINK_X("https://en.wikipedia.org/wiki/ICFP_Programming_Contest", "ICFP Programming Contest - Wikipedia")
)

SECTION_X(1, "Blogs and people",
	LINK_X("https://pbrisbin.com/"         , "pbrisbin dot com"       )
	LINK_X("https://eli.thegreenplace.net/", "Eli Bendersky's website")
)

SECTION_X(1, "Music",
	LINK_X("https://www.newgrounds.com/search/conduct/audio?sort=views-desc&user=Rukkus", "Rukkus I love you where are you")
	LINK_X("https://www.youtube.com/user/TheWickedNorth"                                , "TheWickedNorth - YouTube"       )
	LINK_X("https://www.youtube.com/user/neuIlaryRheinKlange"                           , "neuIlaryRheinKlange - YouTube"  )
	LINK_X("https://www.youtube.com/user/IlaryRhineKlange/featured"                     , "IlaryRhineKlange - YouTube"     )
	LINK_X("https://www.youtube.com/user/avrilfan2213"                                  , "avrilfan2213 - YouTube"         )
)