define(`XGH_MOV',`ifelse(`$#',`4',`dnl
`'define(`XGH_MOV___$1___WIKIDATA',`$2')dnl
`'define(`XGH_MOV___$1___YEAR',`$3')dnl
`'define(`XGH_MOV___$1___TITLE',`$4')dnl
')')dnl
define(`XGH_MOVI',`XGH_MOV($@)')dnl
define(`XGH_MOVIX',`XGH_MOV(shift(shift($@)))')dnl
define(`XGH_HUL',`$*')dnl
define(`XGH_UL',`$*')dnl
define(`XGH_HAUTHOR',`XGH_AUTHOR(shift($@))')dnl
define(`XGH_AUTHOR_N',`define(`XGH_AUTHOR___$2',`$3')`'XGH_CONT2(`AUTHOR2',$@)')dnl
define(`XGH_AUTHOR_P',`XGH_CONT1(`AUTHOR2',$@)')dnl
define(`XGH_AUTHOR_R',`XGH_CONT1(`AUTHOR2',$@)')dnl
define(`XGH_AUTHOR_S',`XGH_AUTHOR($@)')dnl
divert(-1)
