XGH_TIT(`Dead interests')
XGH_HUL(`2',`Electronics, embedded systems, esoteric/niche machines',`dnl
XGH_LIAL(`https://mathweb.ucsd.edu/~sbuss/CourseWeb/Math268_2013W/Bennett_Reversibiity.pdf')
XGH_LIA(`https://wiki.osdev.org/Main_Page',`Expanded Main Page - OSDev Wiki')
XGH_LIAL(`https://developer.arm.com/documentation/dui0801/h/A64-Floating-point-Instructions/FJCVTZS')
XGH_LIAL(`http://platohistory.org/')
XGH_LIAL(`https://sdl-hercules-390.github.io/html/')
XGH_LIAL(`https://en.wikipedia.org/wiki/Open-channel_SSD')
XGH_LIAL(`https://en.wikipedia.org/wiki/Sch%C3%B6nhage%E2%80%93Strassen_algorithm')
XGH_LIAL(`http://www.visual6502.org/JSSim/index.html')
XGH_LIAL(`https://web.archive.org/web/20081024223940/http://www.trinary.cc/Tutorial/Tutorial.htm')
XGH_LIA(`https://www.youtube.com/channel/UClT57Bq5io_kABtihe67C7w/videos',`All Electronics - YouTube')
XGH_LIA(`https://www.4004.com/',`4004')
XGH_LIA(`https://www.j-core.org/',`J-core')
XGH_LIA(`http://www.apollo-core.com/',`APOLLO 68080')
XGH_LIA(`http://nandgame.com/',`NandGame - Build a computer from scratch')
XGH_LIA(`https://eater.net/',`Ben Eater')
XGH_LIA(`https://github.com/riscv-boom/riscv-boom',`SonicBOOM: The Berkeley Out-of-Order Machine')
XGH_LIA(`https://www.youtube.com/watch?v=PGqCeSjNuTY',`Anton: A Special-Purpose Machine That Achieves a Hundred-Fold Speedup in Biomolecular Simulations - YouTube')
XGH_LIAL(`https://buildroot.org/')
XGH_LIAL(`https://wiki.xxiivv.com/site/uxn.html')
XGH_LIAL(`https://www.cse.chalmers.se/~patrikj/poly/')
XGH_LIA(`https://www.youtube.com/c/FastbitEmbeddedBrainAcademy/videos',`Fastbit Embedded Brain Academy - YouTube')
XGH_LIA(`https://ptolemy.berkeley.edu/projects/embedded/pubs/downloads/',`Embedded Downloads')
XGH_LIAL(`https://www.youtube.com/@moshixmainframechannel/videos')
XGH_LIAL(`https://www.youtube.com/watch?v=45X4VP8CGtk')
XGH_LIAL(`https://github.com/xoreaxeaxeax/movfuscator')
XGH_LIAL(`https://pwnednetwork.com/public/pdf/mov.pdf')
')
XGH_HUL(`2',`Arts and 3D modelling',`dnl
XGH_LIAL(`https://github.com/bezo97/IFSRenderer')
XGH_LIAL(`https://github.com/AnimatorPro/Animator-Pro/')
XGH_LIA(`https://www.youtube.com/playlist?list=PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6',`Blender Fundamentals 2.8')
XGH_LIA(`https://cgsociety.org/',`CGSociety')
XGH_LIA(`https://blenderartists.org/',`Blender Artists Community')
XGH_LIA(`https://prodesigntools.com/',`ProDesignTools - Helping Adobe<sup>&reg;</sup> Users since 2009')
')
XGH_HUL(`2',`LaTeX',`dnl
XGH_LIA(`https://www.tablesgenerator.com/',`TablesGenerator.com')
XGH_LIA(`https://www.overleaf.com/',`Overleaf, Online LaTeX Editor')
XGH_LIA(`https://www.codecogs.com/latex/eqneditor.php?lang=pt-br',`Editor Online de Equações LaTeX - crie, integre e baixe')
XGH_LIA(`https://code.google.com/archive/p/mdtufsm-ppgi/source/default/source',`Google Code Archive - Long-term storage for Google Code Project Hosting.')
XGH_LI(`TeXstudio')
')
XGH_HUL(`2',`Natural language processing (NLP)',`dnl
XGH_LIAL(`https://web.archive.org/web/20220121065533/http://www2.tulane.edu/~howard/')
XGH_LIA(`https://nlpprogress.com/',`Tracking Progress in Natural Language Processing | NLP-progress')
XGH_LIA(`https://en.wikipedia.org/wiki/Wikipedia:Language_recognition_chart',`Wikipedia:Language recognition chart - Wikipedia')
')
XGH_HUL(`2',`Programming languages',`dnl
XGH_LI(`OPS5')
XGH_LIAL(`https://github.com/adobe-research/ActionScript4/blob/master/as4wp/AS4wp121031.pdf')
XGH_LIAL(`https://github.com/Co-dfns/Co-dfns')
XGH_LIAL(`https://jsisweird.com/')
XGH_LI(`fusion Haskell')
XGH_LIAL(`https://www.youtube.com/watch?v=vfDazZfxlNs')
XGH_LIAL(`https://craftinginterpreters.com/')
XGH_LIAL(`https://github.com/matz/spinel')
XGH_LIAL(`https://en.wikipedia.org/wiki/FRACTRAN')
XGH_LIAL(`https://www.more-magic.net/posts/scheme-c-integration.html')
XGH_LIAL(`https://lists.libreplanet.org/archive/html/chicken-users/2004-06/msg00065.html')
XGH_LIAL(`https://github.com/manuel-serrano/bigloo/tree/master/examples/Embedded')
XGH_LIAL(`https://web.archive.org/web/20051222001627/http://www.lib.uchicago.edu/keith/crisis/crisis.html')
XGH_LIA(`http://fare.tunes.org/LispM.html',`A few things I know about LISP Machines')
XGH_LIA(`https://llk.media.mit.edu/courses/readings/scratch-proposal-v2.pdf',`Microsoft Word - proposal-handout v2.doc')
XGH_LIA(`https://vfxforth.com/',`: VFX forth ;')
XGH_LIA(`https://cr.yp.to/qhasm.html',`qhasm: tools to help write high-speed software')
XGH_LIA(`http://lilypond.org/',`LilyPond – Music notation for everyone')
XGH_LIA(`https://www.eiffel.com/',`Home | Eiffel Software - The Home of EiffelStudio')
XGH_LIA(`https://github.com/xyproto/battlestar',`xyproto/battlestar: A different take on Assembly')
XGH_LIA(`https://www.learncpp.com/',`Learn C++')
XGH_LIA(`http://book.realworldhaskell.org/read/',`Real World Haskell')
XGH_LIA(`https://downloads.haskell.org/~ghc/latest/docs/html/libraries/',`Haskell Hierarchical Libraries')
XGH_LIA(`http://lambda-the-ultimate.org/',`Lambda the Ultimate | Programming Languages Weblog')
XGH_LI(`Harelang')
XGH_LI(`Nim')
XGH_LI(`Odin')
XGH_LI(`Zig')
XGH_LI(`Rust')
XGH_LI(`Joi')
XGH_LI(`Erlang')
XGH_LI(`Dafny')
')
XGH_HUL(`3',`Parsers',`dnl
XGH_LIAL(`https://docs.godotengine.org/en/stable/about/faq.html`#'what-were-the-motivations-behind-creating-gdscript')
XGH_LIAL(`https://en.wikipedia.org/wiki/Most_vexing_parse')
XGH_LIAL(`https://web.archive.org/web/20120930202629/http://www.research.ibm.com/XML/IBM_Zurich_XML_Accelerator_Engine_paper_2004May04.pdf')
XGH_LIAL(`https://web.archive.org/web/20080622054818/http://www-306.ibm.com/software/integration/datapower/xa35/')
XGH_LIA(`https://tomassetti.me/',`Our articles - Strumenta')
XGH_LIA(`https://tomassetti.me/antlr-mega-tutorial/',`The ANTLR Mega Tutorial')
XGH_LIA(`https://tomassetti.me/resources-create-programming-languages/',`68 Resources on creating programming languages')
XGH_LIA(`https://github.com/antlr/grammars-v4/',`antlr/grammars-v4: Grammars written for ANTLR v4')
XGH_LIA(`http://www.inf.puc-rio.br/~roberto/lpeg/',`LPeg - Parsing Expression Grammars For Lua')
XGH_LIA(`https://tdop.github.io/',`TDOP Pratt')
XGH_LIA(`http://crockford.com/javascript/tdop/tdop.html',`Top Down Operator Precedence')
XGH_LIA(`https://pdos.csail.mit.edu/~baford/packrat/thesis/',`Packrat Parsing: a Practical Linear-Time Algorithm with Backtracking')
XGH_LIA(`https://www.piumarta.com/software/peg/',`peg/leg')
')
XGH_HUL(`2',`Literal undiagnosed untreated undisguised schizophrenia',`dnl
XGH_LIA(`https://isynchronise.com/',`isynchronise – the home of synchronic computation')
XGH_LI(`Gangstalking, targeted individual (TI)')
XGH_LI(`GameB')
')
XGH_HUL(`2',`Cybersecurity',`dnl
XGH_LIAL(`https://phrack.org/issues/71/6')
XGH_LIAL(`https://github.com/JuliaPoo/Artfuscator')
XGH_LIAL(`https://localmess.github.io/')
XGH_LIAL(`https://www.zeropartydata.es/p/localhost-tracking-explained-it-could')
XGH_LIAL(`https://github.com/screetsec/TheFatRat')
XGH_LIAL(`https://secret.club/2021/01/15/bitlocker-bypass.html')
XGH_LIAL(`https://www.bleepingcomputer.com/news/security/microsoft-admits-to-signing-rootkit-malware-in-supply-chain-fiasco/')
XGH_LIAL(`https://trigger.dev/blog/shai-hulud-postmortem')
XGH_LIAL(`https://github.com/byt3bl33d3r/OffensiveNim')
XGH_LIAL(`https://hacktricks.wiki')
XGH_LIA(`https://rada.re/n/radare2.html',`radare2')
XGH_LIA(`https://www.ollydbg.de/',`OllyDbg v1.10')
')
XGH_HUL(`2',`Artificial Intelligence',`dnl
XGH_LIAL(`https://leekwars.com/')
XGH_LIAL(`https://www.red3d.com/cwr/steer/')
XGH_LIA(`https://github.com/codeplea/genann',`GitHub - codeplea/genann: simple neural network library in ANSI C')
XGH_LIA(`http://leenissen.dk/fann/wp/',`Fast Artificial Neural Network Library (FANN)')
XGH_LIA(`http://lwneuralnet.sourceforge.net/',`Lightweight Neural Network')
')
XGH_HUL(`2',`College stuff',`dnl
XGH_LIAL(`http://www.penta.ufrgs.br/edu/telelab/2/war-of-t.htm')
XGH_LIA(`http://www-usr.inf.ufsm.br/~benhur/l12020a/',`ELC1065 - Laboratório de Programação I - UFSM')
')
XGH_HUL(`2',`Crypto',`dnl
XGH_LIA(`https://bitcoinbook.info/',`Mastering Bitcoin – The Bitcoin Book – Programming the Open Blockchain')
XGH_LIA(`https://bitcointalk.org/index.php?topic=375643.0',`I AM HODLING')
XGH_LIA(`https://challenges.ethereum.org/',`Ethereum Bounties')
')
XGH_HUL(`2',`Actual crypto',`dnl
XGH_LI(`Bellare & Hoang, 2024, Efficient Schemes for Committing Authenticated Encryption')
XGH_LI(`ChaCha20-Poly1305')
XGH_LI(`CMT-4 scheme')
XGH_LI(`SipHash')
XGH_LI(`Loss, Limmer, Gernler 2009, "The drunken bishop: An analysis of the OpenSSH fingerprint visualization algorithm"')
XGH_LIAL(`https://en.wikipedia.org/wiki/Confidential_computing')
XGH_LIAL(`https://github.com/C2SP/wycheproof')
XGH_LI(`BIP39, EFF wordlists')
XGH_LIAL(`https://safecurves.cr.yp.to/')
XGH_LIAL(`https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/')
XGH_LIAL(`https://csrc.nist.gov/csrc/media/events/workshop-on-cybersecurity-in-a-post-quantum-world/documents/papers/session3-kate-paper.pdf')
XGH_LIAL(`https://forum.torproject.org/t/tor-relays-post-quantum-cryptography-in-tors-tls-layer-help-needed/21288')
')
XGH_HUL(`2',`Pseudo-intellectualism',`dnl
XGH_LI(`https://www.newgrounds.com/bbs/topic/1559091/37#bbspost28369325_post_text')
XGH_LIAL(`https://open.spotify.com/show/3n2o8vpsRalBeU5U7kWbLX')
XGH_LIAL(`https://www.musictheory.net/exercises')
XGH_LIAL(`https://www.nature.com/articles/s41467-025-59313-0')
XGH_LIAL(`https://en.wikipedia.org/wiki/How_to_Write_History')
XGH_LIAL(`https://web.archive.org/web/20220526060311/https://abstrusegoose.com/332')
XGH_LIAL(`https://www.amazon.com/Kicking-Away-Ladder-Development-Perspective/dp/1843310279')
XGH_LIAL(`https://philpapers.org/')
XGH_LIAL(`https://www.physicsforums.com/media/categories/physics-technical.1/')
XGH_LIAL(`https://en.wikipedia.org/wiki/Russell_L._Ackoff')
XGH_LIAL(`https://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/')
XGH_LIA(`http://bastiat.org/en/twisatwins.html',`That Which is Seen, and That Which is Not Seen; by Frederic Bastiat')
XGH_LIA(`https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/',`As We May Think - The Atlantic')
XGH_LIA(`https://predictionbook.com/',`PredictionBook: How sure are you?')
XGH_LIAL(`https://www.amazon.ca/Anti-Oedipus-Capitalism-Schizophrenia-Gilles-Deleuze/dp/0143105825')
')
XGH_HUL(`2',`Tech support',`dnl
XGH_LIAL(`https://www.supergrubdisk.org/super-grub2-disk/')
XGH_LIA(`https://gbatemp.net/threads/medicat-usb-a-multiboot-linux-usb-for-pc-repair.361577/',`MediCat USB - A Multiboot Linux USB for PC Repair')
XGH_LIA(`https://github.com/ventoy/Ventoy',`ventoy/Ventoy: A new bootable USB solution.')
XGH_LIA(`https://web.archive.org/web/20180711192755/http://mirror.corenoc.de/digitalrivercontent.net/',`Microsoft DigitalRiver Mirror')
')
XGH_HUL(`2',`Smartphone ROM hacking',`dnl
XGH_LIA(`https://wiki.postmarketos.org/wiki/Motorola_Moto_G4_Play_(motorola-harpia)',`Motorola Moto G4 Play (motorola-harpia) - postmarketOS')
')
XGH_HUL(`2',`Minimalist software, distros, package managers, nerd drama, chronically/terminally online worries, software activism',`dnl
XGH_LIAL(`https://lore.kernel.org/lkml/CAHk-=wjajMJyoTv2KZdpVRoPn0LFZ94Loci37WLVXmMxDbLOjg@mail.gmail.com')
XGH_LIAL(`https://lkml.org/lkml/2025/2/6/404')
XGH_LIAL(`https://wiki.debian.org/DontBreakDebian')
XGH_LIAL(`https://theoutline.com/post/2571/no-one-makes-a-living-on-patreon')
XGH_LIAL(`https://skarnet.org/poweredby.html')
XGH_LIAL(`https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819703')
XGH_LIAL(`https://www.youtube.com/watch?v=OmVHkL0IWk4')
XGH_LIAL(`https://wiki.mozilla.org/Performance/Avoid_SQLite_In_Your_Next_Firefox_Feature')
XGH_LIAL(`https://lobste.rs/s/xt82a0/performance_avoid_sqlite_your_next')
XGH_LIAL(`https://hg-edge.mozilla.org/mozilla-central/rev/6b064f9f6e10b25bf2edc916b1b9a8b78cff0465')
XGH_LIAL(`http://islinuxaboutchoice.com/')
XGH_LIAL(`https://lkml.org/lkml/2014/8/12/459')
XGH_LIAL(`https://chrisdown.name/2018/01/02/in-defence-of-swap.html')
XGH_LIAL(`https://web.stanford.edu/~ouster/cgi-bin/cs140-spring20/pintos/pintos_1.html')
XGH_LIAL(`https://www.theregister.com/2025/12/23/unix_v4_tape_successfully_recovered/')
XGH_LIAL(`https://blogs.gentoo.org/mgorny/2025/11/30/one-jobserver-to-rule-them-all/')
XGH_LIAL(`https://without-systemd.org/wiki/index_php/Arguments_against_systemd/')
XGH_LIAL(`https://blogs.gnome.org/adrianvovk/2025/06/10/gnome-systemd-dependencies/')
XGH_LIA(`https://learnbchs.org/',`BCHS: BSD, C, httpd, SQLite')
XGH_LIA(`https://suckless.org/rocks/',`software that sucks less')
XGH_LIA(`https://research.swtch.com/version-sat',`research!rsc: Version SAT')
XGH_LIA(`https://michael.stapelberg.ch/posts/2019-08-17-linux-package-managers-are-slow/',`Linux package managers are slow (2019) - Michael Stapelberg')
XGH_LIAL(`https://node-os.com/')
XGH_LIAL(`https://www.youtube.com/watch?v=RIctzAQOe44')
XGH_LIAL(`https://fireborn.mataroa.blog/blog/i-want-to-love-linux-it-doesnt-love-me-back-post-4-wayland-is-growing-up-and-now-we-dont-have-a-choice/')
XGH_LIAL(`https://harpers.org/archive/2025/01/the-ghosts-in-the-machine-liz-pelly-spotify-musicians/')
XGH_LIA(`https://web.archive.org/web/20151208143727/https://github.com/opal/opal/issues/941',`Transphobic maintainer should be removed from project · Issue `#'941 · opal/opal · GitHub')
XGH_LIA(`https://web.archive.org/web/20151210081611/https://github.com/opal/opal/issues/942',`Create a Code of Conduct · Issue `#'942 · opal/opal · GitHub')
XGH_LIA(`gemini://gemini.circumlunar.space/docs/specification.gmi',`Project Gemini Speculative specification')
XGH_LIA(`https://www.wired.com/story/roblox-online-games-irl-fascism-roman-empire/')
')
XGH_HUL(`2',`Services',`dnl
XGH_LIA(`https://sourcehut.org/',`sourcehut - the hacker@aq@s forge')
XGH_LIA(`https://www.rsync.net/index.html',`rsync - Cloud Storage for Offsite Backup')
XGH_LIA(`https://www.flickr.com/',`Flickr')
XGH_LIA(`https://github.com/borgbackup/borg',`GitHub - borgbackup/borg')
')
XGH_HUL(`2',`Art',`dnl
XGH_LIAL(`http://www.segerman.org/')
XGH_LIAL(`https://art.z97.io/')
XGH_LIAL(`https://www.youtube.com/watch?v=5XyNe8UESTs')
XGH_LIAL(`https://en.wikipedia.org/wiki/Survival_Research_Laboratories')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Hieronymus_Bosch')
XGH_LI(`corpse paint')
XGH_LIAL(`https://karlsims.com/')
XGH_LIA(`https://commons.wikimedia.org/wiki/Category:William-Adolphe_Bouguereau',`William-Adolphe Bouguereau')
XGH_LIA(`http://www.art.net/',`Art.Net (also known as "Art on the Net")')
XGH_LIAL(`http://patriciogonzalezvivo.com')
XGH_LI(`Jeff Lee Johnson (paintings)')
XGH_LIAL(`https://www.youtube.com/@PerfectScarecrow')
')
XGH_HUL(`3',`Web art',`dnl
XGH_LIAL(`https://urlsnake.com/')
XGH_LIAL(`https://archive.is/20250201101356/https://www.newyorker.com/humor/daily-shouts/how-to-draw-a-horse')
XGH_LIA(`http://subgenius.com/pam1/pamphlet_p1.html',`Pamphlet `#'1 - page 1')
XGH_LIA(`https://www.jwz.org/dadadodo/',`DadaDodo')
XGH_LIA(`https://parahumans.wordpress.com/',`Worm | A Complete Web Serial')
XGH_LIA(`http://home.mcom.com/people/paquin/',`Temple @aq@O@aq@ Pacman')
XGH_LIA(`https://www.jwz.org/webcollage/',`WebCollage: Exterminate All Rational Thought')
')
XGH_HUL(`2',`Doing research',`dnl
XGH_LIA(`https://www.sbc.org.br/documentos-da-sbc/category/169-templates-para-artigos-e-ca%20pitulos-de-livros',`Templates para Artigos e Capitulos de Livros')
XGH_LIA(`https://www.edx.org/',`edX')
XGH_LIA(`https://pt.coursera.org/',`Coursera')
XGH_LIA(`https://www.ufsm.br/orgaos-suplementares/biblioteca/',`Bibliotecas UFSM')
XGH_LIA(`https://www.elsevier.com/books-and-journals',`Elsevier')
XGH_LIA(`https://www.acm.org/',`Association for Computing Machinery')
XGH_LIA(`https://ieeexplore.ieee.org/Xplore/home.jsp',`IEEE Xplore')
XGH_LIA(`https://www.ufsm.br/orgaos-executivos/agittec',`AGITTEC – Agência de Inovação e Transferência de Tecnologia')
XGH_LIA(`https://www.orbit.com/',`Orbit')
XGH_LIA(`https://www.epo.org/searching-for-patents.html',`EPO')
XGH_LIA(`https://www.uspto.gov/',`United States Patent and Trademark Office')
XGH_LIA(`https://www.gov.br/inpi/pt-br',`Instituto Nacional de Propriedade Industrial')
')
XGH_HUL(`2',`Demos',`dnl
XGH_LIA(`https://joshdata.me/iceberger.html',`Iceberger')
')
XGH_HUL(`2',`Blogs and people',`dnl
XGH_LIAL(`https://www.muppetlabs.com/~breadbox/')
XGH_LIAL(`https://en.wikipedia.org/wiki/Christopher_Strachey')
XGH_LIAL(`https://web.archive.org/web/20260611173707/https://eklitzke.org/')
XGH_LIAL(`https://liuliu.me')
XGH_LIAL(`http://recp.me/')
XGH_LIAL(`https://danielabrecht.ch/')
XGH_LI(`http://levien.com/')
XGH_LIAL(`https://www.ayman-badawi.com/')
XGH_LIAL(`https://www.janko.at/')
XGH_LIAL(`https://www.s-johansson.org/')
XGH_LIAL(`https://www.shamusyoung.com/twentysidedtale/')
XGH_LIA(`https://instinctive.eu/',`Natacha Porté')
XGH_LIAL(`https://dbbd.sg/blog/')
XGH_LIAL(`https://blog.demofox.org/')
XGH_LIAL(`http://number-none.com/product/')
XGH_LIAL(`http://www.datagenetics.com/blog.html')
XGH_LIAL(`https://www.thomas-huehn.com/')
XGH_LIAL(`https://blog.cr.yp.to/index.html')
XGH_LIA(`https://research.swtch.com/',`research!rsc')
XGH_LIA(`https://www.internalpointers.com/',`Internal Pointers - Internal Pointers')
XGH_LIA(`https://fabiensanglard.net/',`Fabien Sanglard@aq@s Website')
XGH_LIA(`https://sanctum.geek.nz/arabesque/',`Arabesque | Systems, Tools, and Terminal Science')
XGH_LIA(`https://luna.phonk.net',`Welcome to Phonk.net')
XGH_LIA(`https://fexpr.blogspot.com/',`Structural insight')
XGH_LIA(`http://www.wheaty.net/',`Wheaty Productions Inc.')
XGH_LIA(`https://lcamtuf.coredump.cx/',`[lcamtuf.coredump.cx]')
XGH_LIA(`http://jon-jacky.github.io/home/links.html',`Interesting web sites')
XGH_LIA(`http://www.etalabs.net/',`Eta Labs')
XGH_LIA(`http://filter24.org/',`.filter24 : music + technology from rob buse')
XGH_LIA(`https://www.shlomifish.org/',`Shlomi Fish’s Homepage')
XGH_LIA(`http://www.kegel.com/',`Dan Kegel@aq@s Web Hostel')
XGH_LIA(`https://nick-black.com/dankwiki/index.php/Hack_on',`Hack on')
XGH_LIA(`https://eli.thegreenplace.net/',`Eli Bendersky@aq@s website')
XGH_LIA(`https://pbrisbin.com/',`pbrisbin dot com')
XGH_LIAL(`https://andrewkelley.me/')
XGH_LIAL(`https://www.jenlowe.net/')
')
XGH_HUL(`2',`Online communities',`dnl
XGH_LI(`SDF Public Access Unix System')
XGH_LIA(`https://bbs.archlinux.org/index.php',`Arch Linux Forums')
XGH_LIAL(`https://handmade.network/')
XGH_LIAL(`https://www.youtube.com/watch?v=rGSFSNt4hqQ')
')
XGH_HUL(`2',`Drugs',`dnl
XGH_LIA(`https://www.shroomery.org/',`Shroomery')
')
XGH_HUL(`2',`Unity and C#',`dnl
XGH_LIAL(`https://web.archive.org/web/20240716145719/https://www.what-could-possibly-go-wrong.com/the-dispatcher-pattern/')
XGH_LIAL(`https://catlikecoding.com/unity/tutorials/movement/')
XGH_LIAL(`https://isdotnetopen.com/')
')
XGH_HUL(`2',`Java',`dnl
XGH_LIAL(`https://web.archive.org/web/20220302162347/https://www.caelum.com.br/apostila-java-orientacao-objetos')
XGH_LIAL(`https://www.alura.com.br/artigos/historia-da-caelum')
')
XGH_HUL(`2',`Gaymer',`dnl
XGH_LIAL(`https://tboi.com/')
XGH_LIAL(`https://noclip.website/')
XGH_LIAL(`https://www.youtube.com/@xellia4087/playlists')
XGH_LIAL(`https://docs.google.com/spreadsheets/d/1yfo-LYDvHMphE4xhdMH2EaB4q1HJ98canRxOqlclIcQ/edit?usp=sharing')
')
XGH_HUL(`2',`Inevitable link dump',`dnl
XGH_LIAL(`https://en.wikipedia.org/wiki/Financial_Information_eXchange')
XGH_LIAL(`https://en.wikipedia.org/wiki/File:ICANN_History_Project_-_Interview_with_Fadi_Chehad%C3%A9,_ICANN_CEO_(2012-2016)_(105E).webm')
XGH_LIAL(`https://www.youtube.com/watch?v=1fKvTyhgCSo')
XGH_LIAL(`https://www.youtube.com/watch?v=P-JjaAh0NeU&t=1s')
XGH_LIAL(`https://arxiv.org/pdf/0802.0634.pdf')
XGH_LIAL(`https://projecteuler.net/')
XGH_LIAL(`https://www.19miracle.org/over-it-is-nineteen/')
XGH_LIAL(`https://gitlab.com/x86-psABIs/x86-64-ABI')
XGH_LIAL(`https://github.com/Antares007/t-machine')
XGH_LIAL(`https://citizenlab.ca/research/uncovering-global-telecom-exploitation-by-covert-surveillance-actors/')
XGH_LIAL(`https://www.youtube.com/watch?v=PilWMc4H1GE')
XGH_LIAL(`https://www.youtube.com/watch?v=OVIl_DJl5NU')
XGH_LIAL(`https://www.youtube.com/watch?v=u3ZlD9J8LeY')
XGH_LIAL(`https://paperpile.com/blog/shortest-papers/')
XGH_LI(`Akon City Scam')
XGH_LI(`Dudão')
XGH_LI(`A noite oficial dos ovnis')
XGH_LI(`Batalha das toninhas')
XGH_LIAL(`https://www.youtube.com/watch?v=yP5ofsKR4NU')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Seteal%C3%A9m')
XGH_LIAL(`https://en.wikipedia.org/wiki/Edward_Mordake')
XGH_LI(`chal toh chaand tak nahi toh shaam tak')
XGH_LI(`canoe made from kevlar and resine')
XGH_LIAL(`http://www.aviation-history.com/index-aircraft.htm')
XGH_LIAL(`https://earth.org/solarpunk/')
XGH_LIAL(`http://www.worldlicenseplates.com/')
XGH_LIAL(`https://en.wikipedia.org/wiki/Nobel_disease')
XGH_LIAL(`https://en.wikipedia.org/wiki/Replication_crisis')
XGH_LIAL(`https://en.wikipedia.org/wiki/Tsundoku')
')
XGH_HUL(`2',`Infinite lore glitch',`dnl
XGH_LIA(`https://home.treasury.gov/policy-issues/financial-sanctions/sanctions-programs-and-country-information',`Sanctions Programs and Country Information | U.S. Department of the Treasury')
XGH_LIAL(`https://seer.ufrgs.br/index.php/aedos/article/view/88452/56679')
XGH_LIAL(`https://www.bbc.com/news/world-asia-china-22278037')
XGH_LIAL(`https://en.wikipedia.org/wiki/Statue_of_Unity')
XGH_LIAL(`https://commons.wikimedia.org/wiki/File:David_Roberts_-_The_Siege_and_Destruction_of_Jerusalem_by_the_Romans_Under_the_Command_of_Titus,_A.D._70.jpg')
XGH_LIAL(`https://en.wikipedia.org/wiki/Bald@aq@s_Leechbook')
XGH_LIAL(`https://en.wikipedia.org/wiki/Thucydides')
XGH_LIAL(`https://en.wikipedia.org/wiki/The_Jewish_War')
XGH_LIAL(`https://en.wikipedia.org/wiki/Babington_Plot')
XGH_LIAL(`https://www.cia.gov/library/abbottabad-compound/index.html')
XGH_LIAL(`https://en.wikipedia.org/wiki/Vallabhbhai_Patel')
XGH_LIAL(`https://en.wikipedia.org/wiki/Dodge_v._Ford_Motor_Co.')
XGH_LIAL(`https://en.wikipedia.org/wiki/Calamity_Jane')
XGH_LIAL(`https://en.wikipedia.org/wiki/Mercury-Redstone_4')
XGH_LIAL(`https://waynehale.wordpress.com/2019/09/25/oops/')
XGH_LIAL(`https://arstechnica.com/space/2024/01/solving-a-nasa-mystery-why-did-space-shuttle-commanders-lock-the-hatch/')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Placa_de_reclama%C3%A7%C3%A3o_a_Ea-nasir')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Mansa_Mu%C3%A7a')
XGH_LIAL(`https://en.wikipedia.org/wiki/Trail_of_Tears')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Wild_Bill_Hickok')
XGH_LIAL(`https://www.jewishvirtuallibrary.org/')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Cabo_Verde')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Gilles_de_Rais')
XGH_LIAL(`https://en.wikipedia.org/wiki/Suchir_Balaji')
XGH_LIAL(`https://en.wikipedia.org/wiki/Cyclosporiasis')
XGH_LIAL(`https://en.wikipedia.org/wiki/Acta_Eruditorum')
XGH_LIAL(`https://en.wikipedia.org/wiki/2022_Paria_diving_disaster')
XGH_LIAL(`https://en.wikipedia.org/wiki/Ho_Chi_Minh_trail')
XGH_LIAL(`https://en.wikipedia.org/wiki/Camp_Century')
XGH_LIAL(`https://en.wikipedia.org/wiki/Battle_of_Agincourt')
XGH_LIAL(`https://en.wikipedia.org/wiki/The_Epoch_Times')
XGH_LIAL(`https://en.wikipedia.org/wiki/Falun_Gong')
XGH_LIAL(`https://www.nbcnews.com/news/world/china-forcefully-harvests-organs-detainees-tribunal-concludes-n1018646')
XGH_LIAL(`https://pt.wikipedia.org/wiki/A%C3%A9cio_(general)')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Maim%C3%B4nides')
')
XGH_HUL(`2',`Meteorology',`dnl
XGH_LIAL(`https://en.wikipedia.org/wiki/South_Atlantic_Anomaly')
XGH_LIAL(`https://en.wikipedia.org/wiki/Foehn_wind')
')
XGH_HUL(`2',`Fashion and aesthetic',`dnl
XGH_LIAL(`https://www.glasseyeart.com/post/seeing-red-a-brief-history-of-red-glass')
XGH_LIAL(`https://en.wikipedia.org/wiki/Uranium_glass')
XGH_LIAL(`https://en.wikipedia.org/wiki/Zoot_suit')
XGH_LIAL(`https://thevou.com/blog')
XGH_LIAL(`https://usgraphics.com/products/berkeley-mono')
XGH_LIAL(`https://en.wikipedia.org/wiki/Paper_embossing')
XGH_LIAL(`https://cari.institute/aesthetics/vectorheart')
')
XGH_HUL(`2',`Funny numbers',`dnl
XGH_LIAL(`https://www.jetbrains.com/lp/devecosystem-2023/c/')
XGH_LIAL(`https://www.usdebtclock.org/')
XGH_LIAL(`https://www.numbeo.com/cost-of-living/country_price_rankings?itemId=17')
XGH_LIAL(`https://iso-9899.info/candide/pisg/c.html')
')
XGH_HUL(`2',`Filthy Frank',`dnl
XGH_LIAL(`https://www.youtube.com/watch?v=dv3_5XaSIXI')
')
XGH_HUL(`2',`Nerd facts, funnies and history',`dnl
XGH_LIA(`http://www.cypherspace.org/adam/shirt/',`perl RSA "munitions" T-Shirt homepage')
XGH_LIA(`https://lore.kernel.org/ksummit/CAHk-=wiB6FJknDC5PMfpkg4gZrbSuC3d391VyReM4Wb0+JYXXA@mail.gmail.com/',`Re: Maintainers / Kernel Summit 2021 planning kick-off - Linus Torvalds')
XGH_LIA(`https://www.unicode.org/L2/L2018/18122-mate-emoji.pdf',`18122-mate-emoji.pdf')
XGH_LI(`Infinite JSON')
XGH_LIAL(`http://www.catb.org/esr/faqs/things-every-hacker-once-knew/')
XGH_LIAL(`https://nohello.net')
XGH_LIAL(`https://stuff.mit.edu/afs/athena/project/w92/www/lesser-known.shtml')
XGH_LIAL(`https://hackerone.com/reports/2298307')
XGH_LIAL(`https://en.wikipedia.org/wiki/Magic_Cap')
XGH_LIAL(`https://www.daniweb.com/programming/software-development/threads/440954/can-t-fix-error-in-my-program')
XGH_LI(`https://arthurbeaulieu.github.io/ORlyGenerator/')
XGH_LI(`https://perdu.com/')
XGH_LI(`https://poudreverte.org/')
XGH_LI(`"Love is sharing a password"')
XGH_LIAL(`https://wiki.debian.org/WhyTheName')
XGH_LIAL(`https://www.uvena.de/gigolo/')
XGH_LI(`emacs=eight megabytes and constantly swapping')
XGH_LI(`EMACS meaning escape-meta-alt-control-shift, of course')
XGH_LIA(`https://hard-drive.net/',`Hard Drive')
')
XGH_HUL(`2',`Biology and medicine',`dnl
XGH_LI(`Horse fact: they sleep for two hours at a time')
XGH_LIAL(`https://www.hokeniryo1.metro.tokyo.lg.jp/shokuhin/eng/hugu/index.html')
XGH_LIAL(`https://evolution.berkeley.edu/what-are-evograms/jaws-to-ears-in-the-ancestors-of-mammals/')
XGH_LIAL(`https://www.elephantvoices.org/the-elephant-ethogram')
XGH_LIAL(`https://www.coursehero.com/study-guides/boundless-biology/somatosensation/')
XGH_LIAL(`https://www.genengnews.com/topics/drug-discovery/t7-oracle-foretells-functional-proteins-by-accelerating-evolution/')
XGH_LIAL(`https://en.wikipedia.org/wiki/Allium_tuberosum')
XGH_LIAL(`https://pt.wikipedia.org/wiki/Optogen%C3%A9tica')
XGH_LIAL(`https://www.nature.com/articles/s41467-024-47356-8')
XGH_LIAL(`https://www.nia.nih.gov/news/large-study-links-gum-disease-dementia')
XGH_LIAL(`https://pubmed.ncbi.nlm.nih.gov/32280099/')
XGH_LIAL(`https://pubmed.ncbi.nlm.nih.gov/32366948/')
XGH_LIAL(`https://pubmed.ncbi.nlm.nih.gov/39115027/')
XGH_LIAL(`https://pmc.ncbi.nlm.nih.gov/articles/PMC6469458/')
')
XGH_HUL(`2',`Former Flash developers, cartoon-related stuff',`dnl
XGH_LIAL(`http://cockroach.se/')
XGH_LIAL(`https://www.roomwithamoose.com/')
')
XGH_HUL(`2',`Floating-point',`dnl
XGH_LIA(`https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html',`What Every Computer Scientist Should Know About Floating-Point Arithmetic')
XGH_LIA(`https://0.30000000000000004.com/',`Floating Point Math')
XGH_LIAL(`https://www.h-schmidt.net/FloatConverter/IEEE754.html')
XGH_LIAL(`https://randomascii.wordpress.com/2012/09/09/game-developer-magazine-floating-point/')
XGH_LIAL(`https://fabiensanglard.net/floating_point_visually_explained/')
XGH_LIAL(`https://float.exposed/0x44bf9400')
')
XGH_HUL(`2',`Events etc.',`dnl
XGH_LI(`38th Chaos Communication Congress')
')
