XGH_TIT(`Dead interests')
XGH_HUL(`2',`Electronics, embedded systems',`dnl
XGH_LIA(`https://www.youtube.com/channel/UClT57Bq5io_kABtihe67C7w/videos',`All Electronics - YouTube')
XGH_LIA(`https://www.4004.com/',`4004')
XGH_LIA(`https://www.j-core.org/',`J-core')
XGH_LIA(`http://www.apollo-core.com/',`APOLLO 68080')
XGH_LIA(`http://nandgame.com/',`NandGame - Build a computer from scratch')
XGH_LIA(`https://eater.net/',`Ben Eater')
XGH_LIA(`https://github.com/riscv-boom/riscv-boom',`SonicBOOM: The Berkeley Out-of-Order Machine')
XGH_LIA(`https://www.youtube.com/watch?v=PGqCeSjNuTY',`Anton: A Special-Purpose Machine That Achieves a Hundred-Fold Speedup in Biomolecular Simulations - YouTube')
XGH_LIA(`https://www.youtube.com/c/FastbitEmbeddedBrainAcademy/videos',`Fastbit Embedded Brain Academy - YouTube')
XGH_LIA(`https://ptolemy.berkeley.edu/projects/embedded/pubs/downloads/',`Embedded Downloads')
')
XGH_HUL(`2',`Arts and 3D modelling',`dnl
XGH_LIA(`https://www.youtube.com/playlist?list=PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6',`Blender Fundamentals 2.8')
XGH_LIA(`https://cgsociety.org/',`CGSociety')
XGH_LIA(`https://blenderartists.org/',`Blender Artists Community')
XGH_LIA(`https://prodesigntools.com/',`ProDesignTools - Helping Adobe<sup>&reg;</sup> Users since 2009')
')
XGH_HUL(`2',`Satire',`dnl
XGH_LIA(`https://hard-drive.net/',`Hard Drive')
')
XGH_HUL(`2',`LaTeX',`dnl
XGH_LIA(`https://www.tablesgenerator.com/',`TablesGenerator.com')
XGH_LIA(`https://www.overleaf.com/',`Overleaf, Online LaTeX Editor')
XGH_LIA(`https://www.codecogs.com/latex/eqneditor.php?lang=pt-br',`Editor Online de Equações LaTeX - crie, integre e baixe')
XGH_LIA(`https://code.google.com/archive/p/mdtufsm-ppgi/source/default/source',`Google Code Archive - Long-term storage for Google Code Project Hosting.')
')
XGH_HUL(`2',`Natural language processing (NLP)',`dnl
XGH_LIA(`https://nlpprogress.com/',`Tracking Progress in Natural Language Processing | NLP-progress')
XGH_LIA(`https://en.wikipedia.org/wiki/Wikipedia:Language_recognition_chart',`Wikipedia:Language recognition chart - Wikipedia')
')
XGH_HUL(`2',`Chronically-online drama',`dnl
XGH_LIA(`https://web.archive.org/web/20151208143727/https://github.com/opal/opal/issues/941',`Transphobic maintainer should be removed from project · Issue `#'941 · opal/opal · GitHub')
XGH_LIA(`https://web.archive.org/web/20151210081611/https://github.com/opal/opal/issues/942',`Create a Code of Conduct · Issue `#'942 · opal/opal · GitHub')
XGH_LIA(`gemini://gemini.circumlunar.space/docs/specification.gmi',`Project Gemini Speculative specification')
')
XGH_HUL(`2',`Programming languages',`dnl
XGH_LIA(`http://fare.tunes.org/LispM.html',`A few things I know about LISP Machines')
XGH_LIA(`https://llk.media.mit.edu/courses/readings/scratch-proposal-v2.pdf',`Microsoft Word - proposal-handout v2.doc')
XGH_LIA(`https://vfxforth.com/',`: VFX forth ;')
XGH_LIA(`https://cr.yp.to/qhasm.html',`qhasm: tools to help write high-speed software')
XGH_LIA(`http://lilypond.org/',`LilyPond – Music notation for everyone')
XGH_LIA(`https://www.eiffel.com/',`Home | Eiffel Software - The Home of EiffelStudio')
XGH_LIA(`https://github.com/xyproto/battlestar',`xyproto/battlestar: A different take on Assembly')
XGH_LIA(`https://www.learncpp.com/',`Learn C++')
XGH_LIA(`http://book.realworldhaskell.org/read/',`Real World Haskell')
XGH_LIA(`https://downloads.haskell.org/~ghc/latest/docs/html/libraries/',`Haskell Hierarchical Libraries')
XGH_LIA(`http://lambda-the-ultimate.org/',`Lambda the Ultimate | Programming Languages Weblog')
XGH_LI(`Harelang')
XGH_LI(`Nim')
XGH_LI(`Odin')
XGH_LI(`Zig')
XGH_LI(`Rust')
XGH_LI(`Joi')
XGH_LI(`Erlang')
XGH_LI(`Dafny')
')
XGH_HUL(`3',`Parsers',`dnl
XGH_LIA(`https://tomassetti.me/',`Our articles - Strumenta')
XGH_LIA(`https://tomassetti.me/antlr-mega-tutorial/',`The ANTLR Mega Tutorial')
XGH_LIA(`https://tomassetti.me/resources-create-programming-languages/',`68 Resources on creating programming languages')
XGH_LIA(`https://github.com/antlr/grammars-v4/',`antlr/grammars-v4: Grammars written for ANTLR v4')
XGH_LIA(`http://www.inf.puc-rio.br/~roberto/lpeg/',`LPeg - Parsing Expression Grammars For Lua')
XGH_LIA(`https://tdop.github.io/',`TDOP Pratt')
XGH_LIA(`http://crockford.com/javascript/tdop/tdop.html',`Top Down Operator Precedence')
XGH_LIA(`https://pdos.csail.mit.edu/~baford/packrat/thesis/',`Packrat Parsing: a Practical Linear-Time Algorithm with Backtracking')
XGH_LIA(`https://www.piumarta.com/software/peg/',`peg/leg')
')
XGH_HUL(`2',`Probably undiagnosed schizophrenia',`dnl
XGH_LIA(`https://isynchronise.com/',`isynchronise – the home of synchronic computation')
')
XGH_HUL(`2',`Cybersecurity',`dnl
')
XGH_HUL(`2',`Artificial Intelligence',`dnl
XGH_LIA(`https://github.com/codeplea/genann',`GitHub - codeplea/genann: simple neural network library in ANSI C')
XGH_LIA(`http://leenissen.dk/fann/wp/',`Fast Artificial Neural Network Library (FANN)')
XGH_LIA(`http://lwneuralnet.sourceforge.net/',`Lightweight Neural Network')
')
XGH_HUL(`2',`College stuff',`dnl
XGH_LIA(`http://www-usr.inf.ufsm.br/~benhur/l12020a/',`ELC1065 - Laboratório de Programação I - UFSM')
')
XGH_HUL(`2',`Crypto',`dnl
XGH_LIA(`https://bitcoinbook.info/',`Mastering Bitcoin – The Bitcoin Book – Programming the Open Blockchain')
XGH_LIA(`https://bitcointalk.org/index.php?topic=375643.0',`I AM HODLING')
XGH_LIA(`https://challenges.ethereum.org/',`Ethereum Bounties')
')
XGH_HUL(`2',`Pseudo-intellectualism',`dnl
XGH_LIA(`http://bastiat.org/en/twisatwins.html',`That Which is Seen, and That Which is Not Seen; by Frederic Bastiat')
XGH_LIA(`https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/',`As We May Think - The Atlantic')
XGH_LIA(`https://predictionbook.com/',`PredictionBook: How sure are you?')
')
XGH_HUL(`2',`Tech support',`dnl
XGH_LIA(`https://gbatemp.net/threads/medicat-usb-a-multiboot-linux-usb-for-pc-repair.361577/',`MediCat USB - A Multiboot Linux USB for PC Repair')
XGH_LIA(`https://github.com/ventoy/Ventoy',`ventoy/Ventoy: A new bootable USB solution.')
XGH_LIA(`https://web.archive.org/web/20180711192755/http://mirror.corenoc.de/digitalrivercontent.net/',`Microsoft DigitalRiver Mirror')
')
XGH_HUL(`2',`Smartphone ROM hacking',`dnl
XGH_LIA(`https://wiki.postmarketos.org/wiki/Motorola_Moto_G4_Play_(motorola-harpia)',`Motorola Moto G4 Play (motorola-harpia) - postmarketOS')
')
XGH_HUL(`2',`Minimalist software, distros, package managers',`dnl
XGH_LIA(`https://learnbchs.org/',`BCHS: BSD, C, httpd, SQLite')
XGH_LIA(`https://suckless.org/rocks/',`software that sucks less')
XGH_LIA(`https://research.swtch.com/version-sat',`research!rsc: Version SAT')
XGH_LIA(`https://michael.stapelberg.ch/posts/2019-08-17-linux-package-managers-are-slow/',`Linux package managers are slow (2019) - Michael Stapelberg')
')
XGH_HUL(`2',`Services',`dnl
XGH_LIA(`https://sourcehut.org/',`sourcehut - the hacker@aq@s forge')
XGH_LIA(`https://www.rsync.net/index.html',`rsync - Cloud Storage for Offsite Backup')
XGH_LIA(`https://www.flickr.com/',`Flickr')
XGH_LIA(`https://github.com/borgbackup/borg',`GitHub - borgbackup/borg')
')
XGH_HUL(`2',`Art',`dnl
XGH_LIA(`https://commons.wikimedia.org/wiki/Category:William-Adolphe_Bouguereau',`William-Adolphe Bouguereau')
XGH_LIA(`http://www.art.net/',`Art.Net (also known as "Art on the Net")')
XGH_LIAL(`http://patriciogonzalezvivo.com')
')
XGH_HUL(`3',`Web art',`dnl
XGH_LIA(`http://subgenius.com/pam1/pamphlet_p1.html',`Pamphlet `#'1 - page 1')
XGH_LIA(`https://www.jwz.org/dadadodo/',`DadaDodo')
XGH_LIA(`https://parahumans.wordpress.com/',`Worm | A Complete Web Serial')
XGH_LIA(`http://home.mcom.com/people/paquin/',`Temple @aq@O@aq@ Pacman')
XGH_LIA(`https://www.jwz.org/webcollage/',`WebCollage: Exterminate All Rational Thought')
')
XGH_HUL(`2',`Doing research',`dnl
XGH_LIA(`https://www.sbc.org.br/documentos-da-sbc/category/169-templates-para-artigos-e-ca%20pitulos-de-livros',`Templates para Artigos e Capitulos de Livros')
XGH_LIA(`https://www.edx.org/',`edX')
XGH_LIA(`https://pt.coursera.org/',`Coursera')
XGH_LIA(`https://www.ufsm.br/orgaos-suplementares/biblioteca/',`Bibliotecas UFSM')
XGH_LIA(`https://www.elsevier.com/books-and-journals',`Elsevier')
XGH_LIA(`https://www.acm.org/',`Association for Computing Machinery')
XGH_LIA(`https://ieeexplore.ieee.org/Xplore/home.jsp',`IEEE Xplore')
XGH_LIA(`https://www.ufsm.br/orgaos-executivos/agittec',`AGITTEC – Agência de Inovação e Transferência de Tecnologia')
XGH_LIA(`https://www.orbit.com/',`Orbit')
XGH_LIA(`https://www.epo.org/searching-for-patents.html',`EPO')
XGH_LIA(`https://www.uspto.gov/',`United States Patent and Trademark Office')
XGH_LIA(`https://www.gov.br/inpi/pt-br',`Instituto Nacional de Propriedade Industrial')
')
XGH_HUL(`2',`Demos',`dnl
XGH_LIA(`https://joshdata.me/iceberger.html',`Iceberger')
')
XGH_HUL(`2',`Blogs and people',`dnl
XGH_LIA(`https://research.swtch.com/',`research!rsc')
XGH_LIA(`https://www.internalpointers.com/',`Internal Pointers - Internal Pointers')
XGH_LIA(`https://fabiensanglard.net/',`Fabien Sanglard@aq@s Website')
XGH_LIA(`https://sanctum.geek.nz/arabesque/',`Arabesque | Systems, Tools, and Terminal Science')
XGH_LIA(`luna.phonk.net',`Welcome to Phonk.net')
XGH_LIA(`https://fexpr.blogspot.com/',`Structural insight')
XGH_LIA(`http://www.wheaty.net/',`Wheaty Productions Inc.')
XGH_LIA(`https://lcamtuf.coredump.cx/',`[lcamtuf.coredump.cx]')
XGH_LIA(`http://jon-jacky.github.io/home/links.html',`Interesting web sites')
XGH_LIA(`http://www.etalabs.net/',`Eta Labs')
XGH_LIA(`http://filter24.org/',`.filter24 : music + technology from rob buse')
XGH_LIA(`https://www.shlomifish.org/',`Shlomi Fish’s Homepage')
XGH_LIA(`http://www.kegel.com/',`Dan Kegel@aq@s Web Hostel')
XGH_LIA(`https://nick-black.com/dankwiki/index.php/Hack_on',`Hack on')
XGH_LIA(`https://eli.thegreenplace.net/',`Eli Bendersky@aq@s website')
XGH_LIA(`https://pbrisbin.com/',`pbrisbin dot com')
XGH_LIAL(`https://andrewkelley.me/')
XGH_LIAL(`https://www.jenlowe.net/')
')
XGH_HUL(`2',`Online communities',`dnl
XGH_LIA(`https://bbs.archlinux.org/index.php',`Arch Linux Forums')
')
XGH_HUL(`2',`Drugs',`dnl
XGH_LIA(`https://www.shroomery.org/',`Shroomery')
')
