#!/bin/bash

out=~/storage/pictures

if [ $# = 1 ]; then
    ragel -pV $1 | dot -Tsvg > $out/${1%.*}.svg && xdg-open $out/${1%.*}.svg
elif [ $# = 2 ]; then
    ragel -pVM $2 $1 | dot -Tsvg > $out/${2%.*}.svg && xdg-open $out/${2%.*}.svg
else
    echo 'you dumbass'
fi
