GAME_X("From the depths", NULL, NULL,
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://fromthedepthsgame.com/"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/268650/From_the_Depths/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/FromTheDepths"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/FromTheDepths/"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/ftd_game"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/FromTheDepthsGame/"))
)
GAME_X("Procelio", NULL, NULL,
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "https://proceliogame.com/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/2Gpbgsw"))
	LOCATION_X(TWITTER, RESOURCE_X(0, NULL, "https://twitter.com/proceliogame"))
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/Procelio/"))
)
GAME_X("Machinecraft", NULL, NULL,
	LOCATION_X(STEAM, RESOURCE_X(0, NULL, "https://store.steampowered.com/app/397100/MachineCraft/"))
)
GAME_X("Robocraft", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/301520/Robocraft/"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCnqw3Vih9tW1twES2XDHPUg"))
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "https://robocraftgame.com/"))
	LOCATION_X(TWITTER, RESOURCE_X(0, NULL, "https://twitter.com/RoboCraftGame"))
	LOCATION_X(TWITCH , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Robocraft"))
)
GAME_X("War Builder League", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/999270/War_Builder_League/"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "http://warbuilder.org/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/Pv4yF6W"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/WarBuilderLeague"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/war_builder"))
)
GAME_X("Dual Universe", NULL, NULL,
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://www.dualthegame.com/"))
	LOCATION_X(FACEBOOK  , RESOURCE_X(0, NULL, "https://www.facebook.com/dualuniverse"))
	LOCATION_X(TWITTER   , RESOURCE_X(0, NULL, "https://twitter.com/dualuniverse"))
	LOCATION_X(SOUNDCLOUD, RESOURCE_X(0, NULL, "https://soundcloud.com/dualuniverse"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/DualUniverse/"))
)
GAME_X("D.R.O.N.E.", NULL, NULL,
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/droneofficial/"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/987020/DRONE_The_Game/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/drone"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/drone_the_game"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/dronethegame/"))
)
GAME_X("Crossout", NULL, NULL,
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "https://crossout.net/"))
	LOCATION_X(TWITTER, RESOURCE_X(0, NULL, "https://twitter.com/CROSSOUT_EN"))
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/Crossout/"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCNh14TBrhjDxYppWS-lwRRw"))
	LOCATION_X(FORUM  , RESOURCE_X(0, NULL, "https://forum.crossout.net/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/QSecDBG"))
	LOCATION_X(TWITCH , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Crossout"))
)
GAME_X("StarMade", NULL, NULL,
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.star-made.org"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/star-made"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/244770/StarMade/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/Starmade/"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCnMb0GvWwQmsesx40WJ3Ygw"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/SXbkYpU"))
)
GAME_X("Kerbal Space Program", NULL, NULL,
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://www.kerbalspaceprogram.com/"))
	LOCATION_X(STEAM     , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/220200/Kerbal_Space_Program/"))
	LOCATION_X(FORUM     , RESOURCE_X(0, NULL, "https://forum.kerbalspaceprogram.com/"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://wiki.kerbalspaceprogram.com/wiki/Main_Page"))
	LOCATION_X(CURSEFORGE, RESOURCE_X(0, NULL, "https://www.curseforge.com/kerbal/ksp-mods"))
	LOCATION_X(FACEBOOK  , RESOURCE_X(0, NULL, "https://www.facebook.com/kerbalspaceprogram"))
	LOCATION_X(TWITTER   , RESOURCE_X(0, NULL, "https://twitter.com/KerbalSpaceP"))
	LOCATION_X(INSTAGRAM , RESOURCE_X(0, NULL, "https://www.instagram.com/kerbalspacep/"))
	LOCATION_X(TWITCH    , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Kerbal%20Space%20Program"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/KerbalSpaceProgram/"))
	LOCATION_X(YOUTUBE   , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCQ1guiM5U_PbuR_QIoABq0w"))
)
GAME_X("Kerbal Space Program 2", NULL, NULL,
	LOCATION_X(STEAM, RESOURCE_X(0, NULL, "https://store.steampowered.com/app/954850/Kerbal_Space_Program_2/"))
)
GAME_X("Redprints", NULL, NULL, NIL)
GAME_X("KekoRaptor", NULL, NULL,
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCZXrteiGmiYRUqqUGkayNdA"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/as4ra8w"))
)
GAME_X("TerraTech", NULL, NULL,
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "https://www.terratechgame.com/"))
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/285920/TerraTech/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/terratechgame"))
	LOCATION_X(FORUM  , RESOURCE_X(0, NULL, "https://forum.terratechgame.com/index.php"))
	LOCATION_X(WIKI   , RESOURCE_X(0, NULL, "https://terratech.gamepedia.com/TerraTech_Wiki"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCbzoDxqcKfHFBMWFUFILfVw"))
	LOCATION_X(TWITCH , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/TerraTech"))
)
GAME_X("Scrap Mechanic", NULL, NULL,
	LOCATION_X(TWITCH  , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Scrap%20Mechanic"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.scrapmechanic.com/"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/scrapmechanic/"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/ScrapMechanic"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCw9ZSSKtIHj7UmlmRrW0ElA"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/387990/Scrap_Mechanic/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/ScrapMechanic/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/0mR5cg6XoPfz7Rdz"))
)
GAME_X("Besiege", NULL, NULL,
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/Besiege/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/jyCBMcq"))
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/346010/Besiege/"))
	LOCATION_X(WIKI   , RESOURCE_X(0, NULL, "https://besiege.fandom.com/wiki/Besiege_Wiki"))
	LOCATION_X(FORUM  , RESOURCE_X(0, NULL, "http://forum.spiderlinggames.co.uk/index.php"))
	LOCATION_X(TWITCH , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Besiege"))
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "http://www.besiege.spiderlinggames.co.uk/"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UClYnFmFZYH8L0FkWdlSotog"))
)
GAME_X("Empyrion", NULL, NULL,
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCnfnBr9VF7PONKJFPa-Yezw"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/383120/Empyrion__Galactic_Survival/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/empyriongame/"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://empyrion.gamepedia.com/Empyrion:_Galactic_Survival_Wiki"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/EmpyrionGame"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/EmpyrionGame"))
	LOCATION_X(SITE    ,
		RESOURCE_X(0, NULL, "http://empyriongame.com/")
		RESOURCE_X(0, NULL, "https://empyriononline.com/")
	)
)
GAME_X("Avorion", NULL, NULL,
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.avorion.net/"))
	LOCATION_X(FORUM   , RESOURCE_X(0, NULL, "https://forum.avorion.net/"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://avorion.gamepedia.com/Avorion_Wiki"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/avorion/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/avorion/"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/avoriongame/"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCJNz2Dh0ucABZTnjR2D1nQQ"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/445220/Avorion/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/avorion"))
)
GAME_X("Unturned", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/304930/Unturned/"))
	LOCATION_X(FORUM  , RESOURCE_X(0, NULL, "https://forum.smartlydressedgames.com/"))
	LOCATION_X(WIKI   ,
		RESOURCE_X(0, NULL, "https://wiki.smartlydressedgames.com/wiki/Main_Page")
		RESOURCE_X(0, NULL, "https://unturned.fandom.com/wiki/Unturned_Bunker_Wiki")
	)
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/unturned/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/unturned"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCwKxnmjRmG3yj_mnKqdaG_Q"))
	LOCATION_X(TWITCH , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Unturned"))
)
GAME_X("Galactic Junk league", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0      , NULL, "https://store.steampowered.com/app/562590/Galactic_Junk_League/"))
	LOCATION_X(SITE   , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20181103135154/https://galacticjunkleague.com/"))
	LOCATION_X(DISCORD, RESOURCE_X(0      , NULL, "https://discord.com/invite/mxcHbF9"))
	LOCATION_X(REDDIT , RESOURCE_X(0      , NULL, "https://reddit.com/r/galacticjunkleague/"))
	LOCATION_X(FORUM  , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20180821063625/https://forum.galacticjunkleague.com/"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0      , NULL, "https://www.youtube.com/channel/UCZjlltr-WiYg0qRWiUdmY5Q"))
)
GAME_X("Astroneer", NULL, NULL,
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "https://astroneer.space/"))
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/361420/ASTRONEER/"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCrJFM78asLlnrgP0Njjws7A"))
	LOCATION_X(TWITCH   , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Astroneer"))
	LOCATION_X(WIKI     , RESOURCE_X(0, NULL, "https://astroneer.gamepedia.com/Astroneer_Wiki"))
	LOCATION_X(DISCORD  , RESOURCE_X(0, NULL, "https://discord.com/invite/astroneer"))
	LOCATION_X(TWITTER  , RESOURCE_X(0, NULL, "https://twitter.com/astroneergame"))
	LOCATION_X(FACEBOOK , RESOURCE_X(0, NULL, "https://www.facebook.com/astroneergame"))
	LOCATION_X(INSTAGRAM, RESOURCE_X(0, NULL, "https://www.instagram.com/astroneergame/"))
)
GAME_X("REM Project", NULL, NULL,
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "https://remproject.wordpress.com/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/FcE6Vpg"))
)
GAME_X("Cataclysm: Dead Days Ahead", NULL, NULL,
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://cataclysmdda.org/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://old.reddit.com/r/cataclysmdda/"))
	LOCATION_X(GITHUB  , RESOURCE_X(0, NULL, "https://github.com/CleverRaven/Cataclysm-DDA"))
	LOCATION_X(PATREON , RESOURCE_X(0, NULL, "https://www.patreon.com/user/overview?u=15922455"))
	LOCATION_X(DISCORD ,
		RESOURCE_X(0, NULL, "https://discord.com/invite/jFEc7Yp")
		RESOURCE_X(0, NULL, "https://discord.com/invite/byxwnAU")
	)
	LOCATION_X(FORUM   , RESOURCE_X(0, NULL, "https://discourse.cataclysmdda.org/"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UC9B5SrGiWJk6RJzTjghPVWw?pbjreload=101"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "http://cddawiki.chezzo.com/cdda_wiki/"))
	LOCATION_X(FREENODE, RESOURCE_X(0, NULL, "http://webchat.freenode.net/?channels=#CataclysmDDA"))
)
GAME_X("Starbase", NULL, NULL,
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.starbasegame.com/"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/454120/Starbase/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/starbase"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/starbasegame"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/StarbaseGame"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://wiki.starbasegame.com/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/starbase/"))
)
GAME_X("Starship EVO", "aka Skywanderers", NULL,
	LOCATION_X(STEAM      , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/711980/Starship_EVO/"))
	LOCATION_X(DISCORD    , RESOURCE_X(0, NULL, "https://discord.com/invite/starshipevo"))
	LOCATION_X(GITHUB     , RESOURCE_X(0, NULL, "https://github.com/tsunamayo/Starship-EVO"))
	LOCATION_X(REDDIT     , RESOURCE_X(0, NULL, "https://reddit.com/r/StarshipEVO/"))
	LOCATION_X(TWITTER    , RESOURCE_X(0, NULL, "https://twitter.com/TransNeonOrange"))
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "https://skywanderersgame.com/"))
	LOCATION_X(KICKSTARTER, RESOURCE_X(0, NULL, "https://www.kickstarter.com/projects/skywanderers/skywanderers"))
	LOCATION_X(FACEBOOK   , RESOURCE_X(0, NULL, "https://www.facebook.com/Skywanderers-909705905829970/"))
	LOCATION_X(WIKI       , RESOURCE_X(0, NULL, "https://starshipevo.gamepedia.com/"))
)
GAME_X("No Man's Sky", NULL, NULL,
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "https://www.nomanssky.com/"))
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/275850/No_Mans_Sky/"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCLKKdAW7IDYB2tpf_gq0W0Q"))
	LOCATION_X(TWITCH , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/No%20Man%E2%80%99s%20Sky"))
	LOCATION_X(WIKI   , RESOURCE_X(0, NULL, "https://nomanssky.gamepedia.com/"))
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/NoMansSkyTheGame/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/nomanssky"))
	LOCATION_X(TWITTER, RESOURCE_X(0, NULL, "https://twitter.com/nomanssky"))
)
GAME_X("Minecraft", "vanilla or with mods",
	INDENT "Using slime blocks, blocks of redstone and sticky pistons, one can assemble a contraption on Minecraft that can move on its own."
	INDENT "A"
	INDENT "<a href=\"https://duckduckgo.com/?q=%21gv+site%3Ayoutube.com+%22minecraft%22+slime+OR+redstone+OR+robot+OR+machine+moving+OR+walking+OR+flying\">Google query for YouTube videos</a>"
	INDENT "can bring many interesting insights."
	INDENT "Exploiting duplication glitches, these machines are adapted to bomb large parcels of terrain too: see this"
	INDENT "<a href=\"https://www.youtube.com/results?search_query=minecraft%20carpet%20bombing\">YouTube query</a>"
	INDENT "for examples."
	INDENT "Furthermore, command blocks may be used to spawn flying or walking things."
	INDENT "Regarding mods, there are many: check"
	INDENT "<a href=\"https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/wip-mods/1438934-1-2-5-zeppelin-0-31-wip\">Zeppelin</a>,"
	INDENT "<a href=\"https://web.archive.org/web/20180129130022/https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1289952-archimedes-ships-v1-7-banking-ships\">Archimedes' Ships</a> (archive),"
	INDENT "<a href=\"https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2364835-davincis-vessels-previously-archimedes-ships-plus\">Davinci's Vessels</a> (aka Archimedes Ships Plus) and"
	INDENT "<a href=\"https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2761225-valkyrien-warfare-airships-physics-subworlds-and\">Valkyrien Warfare</a> (aka Valkyrien Skies)."
	,
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "https://minecraft.net/"))
	LOCATION_X(WIKI     ,
		RESOURCE_X(0, NULL, "https://minecraft.gamepedia.com/")
		RESOURCE_X(0, NULL, "https://minecraft.fandom.com/")
	)
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/Minecraft/wiki/related"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCQvWX73GQygcwXOTSf_VDVg"))
	LOCATION_X(TWITCH   , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Minecraft"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Minecraft"))
)
GAME_X("Minetest", "with mods",
	INDENT "With the aid of mods, it is possible to build vehicles and fly them on Minetest, and it seems that's actually a core mechanic on the"
	INDENT "<a href=\"https://forum.minetest.net/viewtopic.php?t=20311\">Pandorabox</a>"
	INDENT "server."
	INDENT "To exemplify, see the mods"
	INDENT "<a href=\"https://forum.minetest.net/viewtopic.php?t=6184\">Airship</a>,"
	INDENT "<a href=\"https://forum.minetest.net/viewtopic.php?t=8059\">Meshnode</a>,"
	INDENT "<a href=\"https://forum.minetest.net/viewtopic.php?t=11552\">Flyingships</a>"
	INDENT "and"
	INDENT "<a href=\"https://forum.minetest.net/viewtopic.php?t=20073\">Jumpdrive</a>."
	,
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://www.minetest.net/"))
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=net.minetest.minetest"))
	LOCATION_X(FORUM     , RESOURCE_X(0, NULL, "https://forum.minetest.net/"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://wiki.minetest.net/"))
	LOCATION_X(FREENODE  , RESOURCE_X(0, NULL, "https://wiki.minetest.net/IRC"))
	LOCATION_X(GITHUB    , RESOURCE_X(0, NULL, "https://github.com/minetest"))
	LOCATION_X(DISCORD   , RESOURCE_X(0, NULL, "https://discord.com/invite/Wr6eXU3"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/Minetest/"))
	LOCATION_X(CONTENT   , RESOURCE_X(0, NULL, "https://content.minetest.net/"))
	LOCATION_X(YOUTUBE   , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCLztCYIS09tA9R0wC42zC_Q"))
	LOCATION_X(WIKIPEDIA , RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Minetest"))
)
GAME_X("Garry's Mod", NULL, NULL,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/4000/Garrys_Mod/"))
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/gmod/"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCSAcRxqflcrAoV7kNA_PE4w"))
	LOCATION_X(TWITCH   , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Garry's%20Mod"))
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "https://gmod.facepunch.com/"))
	LOCATION_X(TWITTER  , RESOURCE_X(0, NULL, "https://twitter.com/gmodofficial"))
	LOCATION_X(FACEBOOK , RESOURCE_X(0, NULL, "https://www.facebook.com/grrysmd"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Garry's_Mod"))
)
GAME_X("Roblox", NULL, NULL,
	LOCATION_X(SITE           , RESOURCE_X(0, NULL, "https://www.roblox.com/"))
	LOCATION_X(APP_STORE      , RESOURCE_X(0, NULL, "https://apps.apple.com/app/roblox-mobile/id431946152"))
	LOCATION_X(PLAY_STORE     , RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.roblox.client"))
	LOCATION_X(AMAZON         , RESOURCE_X(0, NULL, "https://www.amazon.com/Roblox-Corporation/dp/B00NUF4YOA"))
	LOCATION_X(XBOX           , RESOURCE_X(0, NULL, "https://www.microsoft.com/p/roblox/bq1tn1t79v9k"))
	LOCATION_X(MICROSOFT_STORE, RESOURCE_X(0, NULL, "https://www.microsoft.com/p/roblox/9nblgggzm6wm"))
	LOCATION_X(YOUTUBE        , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCO_8hF-oulap_6lXy0oXLjg"))
	LOCATION_X(REDDIT         , RESOURCE_X(0, NULL, "https://reddit.com/r/roblox/"))
)
GAME_X("Planets³", "aka Stellar Overload", NULL,
	LOCATION_X(KICKSTARTER, RESOURCE_X(0, NULL, "https://www.kickstarter.com/projects/1247991467/planets3"))
	LOCATION_X(STEAM      ,
		RESOURCE_X(0, NULL, "https://store.steampowered.com/app/397150/Stellar_Overload/")
		RESOURCE_X(0, NULL, "https://steamcommunity.com/sharedfiles/filedetails/?id=236736048")
	)
	LOCATION_X(TWITTER    , RESOURCE_X(0, NULL, "https://twitter.com/PlanetsCube"))
	LOCATION_X(YOUTUBE    , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCr1Lh2p0_FIbF17t5-U9Udg"))
	LOCATION_X(TWITCH     , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Stellar%20Overload"))
)
GAME_X("UPGRADE COMPLETE!", NULL, NULL,
	LOCATION_X(ARMOR_GAMES    , RESOURCE_X(0, NULL, "https://armorgames.com/play/3955/"))
	LOCATION_X(KONGREGATE     , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/ArmorGames/upgrade-complete"))
	LOCATION_X(JAYISGAMES     , RESOURCE_X(0, NULL, "https://jayisgames.com/review/upgrade-complete.php"))
	LOCATION_X(NEWGROUNDS     , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/499812"))
	LOCATION_X(NOT_DOPPLER    , RESOURCE_X(0, NULL, "http://www.notdoppler.com/upgradecomplete.php"))
	LOCATION_X(TV_TROPES      , RESOURCE_X(0, NULL, "https://tvtropes.org/pmwiki/pmwiki.php/VideoGame/UpgradeComplete"))
	LOCATION_X(ADDICTING_GAMES, RESOURCE_X(0, NULL, "https://www.addictinggames.com/action/upgrade-complete"))
	LOCATION_X(BUBBLEBOX      , RESOURCE_X(0, NULL, "https://www.bubblebox.com/play/1420/upgrade-complete.htm"))
	LOCATION_X(MAX_GAMES      , RESOURCE_X(0, NULL, "http://www.maxgames.com/play/upgrade-complete.html"))
	LOCATION_X(FLONGA         , RESOURCE_X(0, NULL, "http://www.flonga.com/play/upgrade-complete.htm"))
	LOCATION_X(CRAZY_GAMES    , RESOURCE_X(0, NULL, "http://www.crazygames.com/game/upgrade-complete"))
)
GAME_X("Upgrade Complete 2", NULL, NULL,
	LOCATION_X(ARMOR_GAMES, RESOURCE_X(0, NULL, "https://armorgames.com/play/11028/upgrade-complete-2"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/ArmorGames/upgrade-complete-2"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/567439"))
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "http://www.crazygames.com/game/upgrade-complete-2"))
)
GAME_X("Upgrade Complete 3", NULL, NULL,
	LOCATION_X(ARMOR_GAMES, RESOURCE_X(0, NULL, "http://armorgames.com/play/17636/upgrade-complete-3mium"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/the_exp/upgrade-complete-3"))
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "http://www.crazygames.com/game/upgrade-complete-3mium"))
)
GAME_X("Dream Car Racing", NULL, NULL,
	LOCATION_X(SITE           , RESOURCE_X(0, NULL, "http://dreamcarracing.com/index.html"))
	LOCATION_X(ADDICTING_GAMES, RESOURCE_X(0, NULL, "https://www.addictinggames.com/car/dream-car-racing"))
	LOCATION_X(SILVER_GAMES   , RESOURCE_X(0, NULL, "https://www.silvergames.com/dream-car-racing"))
	LOCATION_X(KONGREGATE     , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/roko0/dream-car-racing"))
	LOCATION_X(NEWGROUNDS     , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/638197"))
	LOCATION_X(CRAZY_GAMES    , RESOURCE_X(0, NULL, "https://www.crazygames.com/game/dream-car-racing"))
	LOCATION_X(NOT_DOPPLER    , RESOURCE_X(0, NULL, "http://www.notdoppler.com/dreamcarracing.php"))
	LOCATION_X(FLONGA         , RESOURCE_X(0, NULL, "http://www.flonga.com/play/dream-car-racing.htm"))
	LOCATION_X(MAX_GAMES      , RESOURCE_X(0, NULL, "https://www.maxgames.com/game/dream-car-racing.html"))
)
GAME_X("Dream Car Racing 2", NULL, NULL,
	LOCATION_X(SITE        , RESOURCE_X(0, NULL, "http://dreamcarracing.com/dcr2-index.html"))
	LOCATION_X(KONGREGATE  , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/roko0/dream-car-racing-2"))
	LOCATION_X(SILVER_GAMES, RESOURCE_X(0, NULL, "https://www.silvergames.com/en/dream-car-racing-2"))
	LOCATION_X(FLONGA      , RESOURCE_X(0, NULL, "http://www.flonga.com/play/dream-car-racing-2.htm"))
	LOCATION_X(CRAZY_GAMES , RESOURCE_X(0, NULL, "https://www.crazygames.com/game/dream-car-racing-2"))
	LOCATION_X(NEWGROUNDS  , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/651361"))
)
GAME_X("Dream Car Racing EVO", NULL, NULL,
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "http://dreamcarracing.com/dcr3-play.html"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/roko0/dream-car-racing-evo"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/654499"))
	LOCATION_X(FLONGA     , RESOURCE_X(0, NULL, "http://flonga.com/play/dream-car-racing-evo.htm"))
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "https://www.crazygames.com/game/dream-car-racing-evo"))
)
GAME_X("Dream Car Building", "aka Dream Car Racing 3D", NULL,
	LOCATION_X(SITE   ,
		RESOURCE_X(0, NULL, "http://dreamcarracing3d.com/")
		RESOURCE_X(0, NULL, "http://dreamcarbuilder.com/")
	)
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/488550/Dream_Car_Builder/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/ph7nk4j"))
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/DreamCarBuilder/"))
)
GAME_X("Scraps: Modular Vehicle Combat", NULL, NULL,
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "http://www.scrapsgame.com/"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/Nition"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/bestmomentstudio"))
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/350150/Scraps_Modular_Vehicle_Combat/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/Scraps/"))
)
GAME_X("Bubble Tanks Arenas", NULL, NULL,
	LOCATION_X(ARMOR_GAMES, RESOURCE_X(0, NULL, "https://armorgames.com/play/5967/bubble-tanks-arenas"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/herointeractive/bubble-tanks-arenas"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/542156"))
	LOCATION_X(NOT_DOPPLER, RESOURCE_X(0, NULL, "http://www.notdoppler.com/bubbletanksarenas.php"))
	LOCATION_X(FLONGA     , RESOURCE_X(0, NULL, "http://www.flonga.com/play/bubble-tanks-arenas.htm"))
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "http://www.crazygames.com/game/bubble-tanks-arenas"))
	LOCATION_X(JAYISGAMES , RESOURCE_X(0, NULL, "https://jayisgames.com/review/bubble-tanks-arenas.php"))
)
GAME_X("Bubble Tanks 3", NULL, NULL,
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/herointeractive/bubble-tanks-3"))
	LOCATION_X(BUBBLEBOX  , RESOURCE_X(0, NULL, "https://www.bubblebox.com/play/2031/bubble-tanks-3.htm"))
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "http://www.crazygames.com/game/bubble-tanks-3"))
)
GAME_X("Space Arena: Build and Fight!", NULL, NULL,
	LOCATION_X(KONGREGATE, RESOURCE_X(0, NULL, "https://www.kongregate.com/games/HeroCraft_Games/space-arena-build-fight"))
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.herocraft.game.free.spaceshipbattles"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/id1134614037"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/SpaceArena/"))
	LOCATION_X(DISCORD   , RESOURCE_X(0, NULL, "https://discord.com/invite/spacearena"))
)
GAME_X("ShellCore Command: Ep1", NULL, NULL,
	LOCATION_X(KONGREGATE, RESOURCE_X(0, NULL, "https://www.kongregate.com/games/Flashbacker/shellcore-command-ep1-final"))
	LOCATION_X(NEWGROUNDS, RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/527383"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://shellcorecommand2.fandom.com/wiki/ShellCore_Command:_Episode_1:_Newborn"))
)
GAME_X("ShellCore: Skirmish", NULL, NULL,
	LOCATION_X(KONGREGATE, RESOURCE_X(0, NULL, "https://www.kongregate.com/games/Flashbacker/shellcore-command-skirmish"))
	LOCATION_X(NEWGROUNDS, RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/540869"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://shellcorecommand2.fandom.com/wiki/ShellCore_Command:_Skirmish_Special"))
)
GAME_X("ShellCore Command: Ep2", NULL, NULL,
	LOCATION_X(WIKI   , RESOURCE_X(0, NULL, "https://shellcorecommand2.fandom.com/wiki/ShellCore_Command:_Episode_2:_Infection"))
	LOCATION_X(FASTSWF, RESOURCE_X(0, NULL, "http://www.fastswf.com/1PXlrBk"))
)
GAME_X("ShellCore Command Remastered", NULL, NULL,
	LOCATION_X(GITHUB, RESOURCE_X(0, NULL, "https://github.com/rudderbucky/shellcore"))
)
GAME_X("Spore", NULL, NULL,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/17390/SPORE/"))
	LOCATION_X(ORIGIN   , RESOURCE_X(0, NULL, "https://www.origin.com/store/spore/spore"))
	LOCATION_X(SITE     ,
		RESOURCE_X(0, NULL, "http://www.spore.com/")
		RESOURCE_X(0, NULL, "https://www.ea.com/games/spore/spore")
	)
	LOCATION_X(CONTENT  , RESOURCE_X(0, NULL, "http://www.spore.com/sporepedia#qry=all"))
	LOCATION_X(FORUM    ,
		RESOURCE_X(0, NULL, "https://answers.ea.com/t5/Spore/ct-p/spore-en")
		RESOURCE_X(0, NULL, "https://spore.boards.net/")
		RESOURCE_X(0, NULL, "https://www.sporepedia2.com/")
		RESOURCE_X(0, NULL, "http://davoonline.com/phpBB3/")
	)
	LOCATION_X(FACEBOOK , RESOURCE_X(0, NULL, "https://www.facebook.com/Spore"))
	LOCATION_X(TWITTER  , RESOURCE_X(0, NULL, "https://twitter.com/spore"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCkKQmNLuGnyyTi4ik6WsuhQ"))
	LOCATION_X(TWITCH   , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Spore"))
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/Spore/"))
	LOCATION_X(WIKI     , RESOURCE_X(0, NULL, "https://spore.fandom.com/"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://en.wikipedia.org/wiki/Spore_(2008_video_game)"))
)
GAME_X("Thrive", NULL, NULL,
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://revolutionarygamesstudio.com/"))
	LOCATION_X(TWITTER   , RESOURCE_X(0, NULL, "https://twitter.com/thrive_game"))
	LOCATION_X(FACEBOOK  , RESOURCE_X(0, NULL, "https://www.facebook.com/Thrive-182887991751358/"))
	LOCATION_X(GITHUB    , RESOURCE_X(0, NULL, "https://github.com/Revolutionary-Games"))
	LOCATION_X(YOUTUBE   , RESOURCE_X(0, NULL, "https://www.youtube.com/c/RevolutionaryGames"))
	LOCATION_X(DEVIANTART, RESOURCE_X(0, NULL, "https://www.deviantart.com/thrive-game"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/thrive/"))
	LOCATION_X(STEAM     , RESOURCE_X(0, NULL, "https://steamcommunity.com/groups/ThriveGame"))
	LOCATION_X(PATREON   , RESOURCE_X(0, NULL, "https://www.patreon.com/thrivegame"))
	LOCATION_X(FORUM     ,
		RESOURCE_X(0, NULL, "https://forum.revolutionarygamesstudio.com/")
		RESOURCE_X(0, NULL, "https://community.revolutionarygamesstudio.com/")
	)
	LOCATION_X(WIKI      ,
		RESOURCE_X(0, NULL, "https://wiki.revolutionarygamesstudio.com")
		RESOURCE_X(0, NULL, "https://thrive.fandom.com")
	)
	LOCATION_X(INSTAGRAM , RESOURCE_X(0, NULL, "https://www.instagram.com/thrive_game/"))
	LOCATION_X(MOD_DB    , RESOURCE_X(0, NULL, "https://www.moddb.com/games/thrive"))
	LOCATION_X(DISCORD   , RESOURCE_X(0, NULL, "https://discord.com/invite/FZxDQ4H"))
)
GAME_X("Steamlands", NULL, NULL,
	LOCATION_X(NITROME    , RESOURCE_X(0, NULL, "http://www.nitrome.com/games/steamlands/?game=steamlands"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/nitrome/steamlands"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/576274"))
	LOCATION_X(ARMOR_GAMES, RESOURCE_X(0, NULL, "http://armorgames.com/play/12286/steamlands"))
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "http://www.crazygames.com/game/steamlands"))
	LOCATION_X(NOT_DOPPLER, RESOURCE_X(0, NULL, "http://www.notdoppler.com/steamlands.php"))
	LOCATION_X(WIKI       , RESOURCE_X(0, NULL, "https://nitrome.fandom.com/wiki/Steamlands"))
	LOCATION_X(JAYISGAMES , RESOURCE_X(0, NULL, "https://jayisgames.com/review/steamlands.php"))
)
GAME_X("Steamlands Player Pack", NULL, NULL,
	LOCATION_X(NITROME    , RESOURCE_X(0, NULL, "http://www.nitrome.com/games/steamlandsplayerpack/"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/nitrome/steamlands-player-pack"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/598028"))
	LOCATION_X(NOT_DOPPLER, RESOURCE_X(0, NULL, "http://www.notdoppler.com/steamlandsplayerpack.php"))
	LOCATION_X(WIKI       , RESOURCE_X(0, NULL, "https://nitrome.fandom.com/wiki/Steamlands_Player_Pack"))
	LOCATION_X(JAYISGAMES , RESOURCE_X(0, NULL, "https://jayisgames.com/review/steamlands-player-pack.php"))
)
GAME_X("Carbon6"      , NULL, NULL, NIL)
GAME_X("Project Prime", NULL, NULL, NIL)
GAME_X("Wallace & Gromit Present: Wallace’s Workshop", NULL, NULL,
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/aardman/wallace-gromit-present-wallace-s-workshop"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/551438"))
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "https://www.wallaceandgromit.com/games/wallaces-workshop"))
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "https://www.crazygames.com/game/wallace-s-workshop"))
	LOCATION_X(JAYISGAMES , RESOURCE_X(0, NULL, "https://jayisgames.com/review/wallaces-workshop.php"))
)
GAME_X("Banjo-Kazooie: Nuts & Bolts", NULL, NULL,
	LOCATION_X(XBOX         , RESOURCE_X(0      , NULL, "https://marketplace.xbox.com/en-US/Product/Banjo-Kazooie-N-n-B/66acd000-77fe-1000-9115-d8024d5307ed"))
	LOCATION_X(SITE         , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20120723021120/http://banjo-kazooie.com/"))
	LOCATION_X(WIKIPEDIA    , RESOURCE_X(0      , NULL, "https://wikipedia.org/wiki/Banjo-Kazooie:_Nuts_%26_Bolts"))
)
GAME_X("SimpleRockets", NULL, NULL,
	LOCATION_X(STEAM     , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/343090/SimpleRockets/"))
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.jundroo.simplerockets"))
	LOCATION_X(APP_STORE ,
		RESOURCE_X(0, NULL, "https://apps.apple.com/app/simplerockets/id663068211")
		RESOURCE_X(0, NULL, "https://apps.apple.com/us/app/simplerockets/id994253085")
	)
	LOCATION_X(AMAZON    , RESOURCE_X(0, NULL, "https://www.amazon.com/gp/product/B00ELOOYZI/"))
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "http://jundroo.com/app/simplerockets/"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/simplerockets/"))
	LOCATION_X(DISCORD   ,
		RESOURCE_X(0, NULL, "https://discord.com/invite/HFJ6jkp")
		RESOURCE_X(0, NULL, "https://discord.com/invite/ZmnxC3C")
	)
)
GAME_X("SimpleRockets 2", NULL, NULL,
	LOCATION_X(PLAY_STORE  , RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.jundroo.SimpleRockets2"))
	LOCATION_X(STEAM       , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/870200/SimpleRockets_2/"))
	LOCATION_X(APP_STORE   , RESOURCE_X(0, NULL, "https://apps.apple.com/app/simplerockets-2/id1294032921"))
	LOCATION_X(HUMBLE_STORE, RESOURCE_X(0, NULL, "https://www.humblebundle.com/store/simplerockets-2"))
	LOCATION_X(SITE        ,
		RESOURCE_X(0, NULL, "https://www.simplerockets.com/")
		RESOURCE_X(0, NULL, "http://jundroo.com/app/simplerockets-2/")
	)
	LOCATION_X(REDDIT      , RESOURCE_X(0, NULL, "https://reddit.com/r/simplerockets/"))
)
GAME_X("SimplePlanes", NULL, NULL,
	LOCATION_X(PLAY_STORE  , RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.jundroo.SimplePlanes"))
	LOCATION_X(APP_STORE   , RESOURCE_X(0, NULL, "https://apps.apple.com/app/simpleplanes/id823869162"))
	LOCATION_X(STEAM       , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/397340/SimplePlanes/"))
	LOCATION_X(GOG         , RESOURCE_X(0, NULL, "https://www.gog.com/game/simpleplanes"))
	LOCATION_X(HUMBLE_STORE, RESOURCE_X(0, NULL, "https://www.humblebundle.com/store/simpleplanes"))
	LOCATION_X(AMAZON      , RESOURCE_X(0, NULL, "https://www.amazon.com/Jundroo-LLC-SimplePlanes/dp/B00PV0CLWE"))
	LOCATION_X(SITE        ,
		RESOURCE_X(0, NULL, "http://www.simpleplanes.com/")
		RESOURCE_X(0, NULL, "http://jundroo.com/app/simpleplanes/")
	)
	LOCATION_X(REDDIT      , RESOURCE_X(0, NULL, "https://reddit.com/r/SimplePlanes/"))
	LOCATION_X(FREENODE    , RESOURCE_X(0, NULL, "https://kiwiirc.com/nextclient/irc.freenode.net/?#simpleplanes"))
	LOCATION_X(YOUTUBE     , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCydUn0QxrTu0muBgPLxzzow"))
)
GAME_X("Gimbal", NULL, NULL,
	LOCATION_X(STEAM ,
		RESOURCE_X(0, NULL, "https://store.steampowered.com/app/252070/Gimbal/")
		RESOURCE_X(0, NULL, "https://steamcommunity.com/sharedfiles/filedetails/?id=92972168")
	)
	LOCATION_X(SITE  , RESOURCE_X(0, NULL, "http://www.gimbalgame.com/"))
	LOCATION_X(REDDIT, RESOURCE_X(0, NULL, "https://reddit.com/r/Gimbal/"))
	LOCATION_X(WIKI  , RESOURCE_X(0, NULL, "https://gimbal.fandom.com/wiki/Gimbal_Wiki"))
	LOCATION_X(RIZON , RESOURCE_X(0, NULL, "https://qchat.rizon.net/?channels=gimbal"))
)
GAME_X("Reassembly", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/329130/Reassembly/"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.anisopteragames.com/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/8fCjt3J"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCsyCMhln3HM62S6YeW10YyA"))
	LOCATION_X(TWITCH  , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Reassembly"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/Reassembly/"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/reassembly_rqd"))
	LOCATION_X(FORUM   , RESOURCE_X(0, NULL, "https://www.anisopteragames.com/forum/"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/reassemblygame"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/reassembly"))
)
GAME_X("Homebrew - Patent Unknown", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/325420/Homebrew__Patent_Unknown/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/homebrew"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "http://homebrewgame.com/wiki/index.php"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://copybugpaste.wixsite.com/hbvs"))
	LOCATION_X(MOD_DB  , RESOURCE_X(0, NULL, "https://www.moddb.com/games/homebrew/mods"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/homebrew"))
)
GAME_X("IncrediBots", NULL, NULL,
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "http://incredibots.com/if/game.php?v=ib1"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/grubbygames/incredibots"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/470376"))
	LOCATION_X(JAYISGAMES , RESOURCE_X(0, NULL, "https://jayisgames.com/review/incredibots.php"))
	LOCATION_X(MAX_GAMES  , RESOURCE_X(0, NULL, "http://www.maxgames.com/game/incredibots.html"))
	LOCATION_X(NOT_DOPPLER, RESOURCE_X(0, NULL, "http://www.notdoppler.com/incredibots.php"))
	LOCATION_X(BUBBLEBOX  , RESOURCE_X(0, NULL, "https://www.bubblebox.com/play/1206/incredibots.htm"))
	LOCATION_X(WIKIPEDIA  , RESOURCE_X(0, NULL, "https://en.wikipedia.org/wiki/Incredibots"))
	LOCATION_X(REDDIT     , RESOURCE_X(0, NULL, "https://reddit.com/r/IncrediBots/"))
	LOCATION_X(DISCORD    , RESOURCE_X(0, NULL, "https://discord.com/invite/TKPEeCp"))
)
GAME_X("IncrediBots 2", NULL, NULL,
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "http://incredibots.com/if/game.php"))
	LOCATION_X(KONGREGATE , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/grubbygames/incredibots-2"))
	LOCATION_X(NOT_DOPPLER, RESOURCE_X(0, NULL, "http://www.notdoppler.com/incredibots2.php"))
	LOCATION_X(NEWGROUNDS , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/501065"))
	LOCATION_X(BUBBLEBOX  , RESOURCE_X(0, NULL, "https://www.bubblebox.com/play/1433/incredibots-2.htm"))
	LOCATION_X(MAX_GAMES  , RESOURCE_X(0, NULL, "http://www.maxgames.com/play/incredibots-2.html"))
)
GAME_X("IncrediBots 3", NULL, NULL,
	LOCATION_X(SITE, RESOURCE_X(0, NULL, "http://www.incredibots.com/if/game.php?v=ib3"))
)
GAME_X("Airships: Conquer the Skies", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/342560/Airships_Conquer_the_Skies/"))
	LOCATION_X(ITCH_IO , RESOURCE_X(0, NULL, "https://zarkonnen.itch.io/airships"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "http://www.zarkonnen.com/airships"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/zarkonnen_com"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://airshipsconquertheskies.gamepedia.com"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/AirshipsGame/"))
	LOCATION_X(GOG     , RESOURCE_X(0, NULL, "https://www.gog.com/game/airships_conquer_the_skies"))
	LOCATION_X(MOD_DB  , RESOURCE_X(0, NULL, "https://www.moddb.com/games/airships"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/airships"))
)
GAME_X("M.A.V. - Modular Assault Vehicle", NULL, NULL,
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "https://bombdogstudios.com/"))
	LOCATION_X(TWITCH     , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/M.A.V."))
	LOCATION_X(DISCORD    ,
		RESOURCE_X(0, NULL, "https://discord.com/invite/negNA5m")
		RESOURCE_X(0, NULL, "https://discord.com/invite/9ngTuub")
	)
	LOCATION_X(REDDIT     , RESOURCE_X(0, NULL, "https://reddit.com/r/mav/"))
	LOCATION_X(FORUM      , RESOURCE_X(0, NULL, "https://bombdogstudios.com/forums/"))
	LOCATION_X(YOUTUBE    , RESOURCE_X(0, NULL, "https://www.youtube.com/user/BombdogStudios"))
	LOCATION_X(TWITTER    , RESOURCE_X(0, NULL, "https://twitter.com/BombdogStudios"))
	LOCATION_X(FACEBOOK   , RESOURCE_X(0, NULL, "https://www.facebook.com/BombdogStudios"))
	LOCATION_X(TRELLO     , RESOURCE_X(0, NULL, "https://trello.com/b/XAgkxoIK/mav-feature-list"))
	LOCATION_X(WIKI       , RESOURCE_X(0, NULL, "https://bombdogstudios.com/wiki/"))
	LOCATION_X(KICKSTARTER, RESOURCE_X(0, NULL, "https://www.kickstarter.com/projects/1509489292/mav-modular-assault-vehicle"))
	LOCATION_X(STEAM      , RESOURCE_X(0, NULL, "https://steamcommunity.com/sharedfiles/filedetails/?id=213963346"))
	LOCATION_X(WIKIPEDIA  , RESOURCE_X(0, NULL, "https://en.wikipedia.org/wiki/M.A.V._(video_game)"))
)
GAME_X("Istrolid", NULL, NULL,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/449140/Istrolid/"))
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "http://www.istrolid.com/"))
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/istrolid/"))
	LOCATION_X(DISCORD  , RESOURCE_X(0, NULL, "https://discord.com/invite/011Fbi3Zlzrnm2FsY"))
	LOCATION_X(TWITTER  , RESOURCE_X(0, NULL, "https://twitter.com/treeform"))
	LOCATION_X(FACEBOOK , RESOURCE_X(0, NULL, "https://www.facebook.com/istrolid/"))
	LOCATION_X(INSTAGRAM, RESOURCE_X(0, NULL, "https://www.instagram.com/istrolid/"))
	LOCATION_X(WIKI     , RESOURCE_X(0, NULL, "https://istrolid.fandom.com"))
)
GAME_X("Nimbatus", NULL, NULL,
	LOCATION_X(STEAM       ,
		RESOURCE_X(0, NULL, "https://store.steampowered.com/app/383840/Nimbatus__The_Space_Drone_Constructor/")
		RESOURCE_X(0, NULL, "https://store.steampowered.com/app/1243130/Nimbatus__Drone_Creator/")
	)
	LOCATION_X(HUMBLE_STORE, RESOURCE_X(0, NULL, "https://www.humblebundle.com/store/nimbatus-the-space-drone-constructor"))
	LOCATION_X(SITE        , RESOURCE_X(0, NULL, "https://www.nimbatus.ch/"))
	LOCATION_X(DISCORD     , RESOURCE_X(0, NULL, "https://discord.com/invite/nimbatus"))
	LOCATION_X(FORUM       , RESOURCE_X(0, NULL, "https://strayfawnstudio.com/community/"))
	LOCATION_X(TWITTER     , RESOURCE_X(0, NULL, "https://twitter.com/NimbatusGame"))
	LOCATION_X(TWITCH      , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Nimbatus%3A%20The%20Space%20Drone%20Constructor/"))
	LOCATION_X(REDDIT      , RESOURCE_X(0, NULL, "https://reddit.com/r/NimbatusGame/"))
	LOCATION_X(KICKSTARTER , RESOURCE_X(0, NULL, "https://www.kickstarter.com/projects/strayfawnstudio/nimbatus-the-space-drone-constructor"))
)
GAME_X("Cosmoteer", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/799600/Cosmoteer_Starship_Architect__Commander/"))
	LOCATION_X(ITCH_IO , RESOURCE_X(0, NULL, "https://walternaterealities.itch.io/cosmoteer"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://cosmoteer.net/"))
	LOCATION_X(FORUM   , RESOURCE_X(0, NULL, "https://forum.cosmoteer.net/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/cosmoteer"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/Cosmoteer/"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://wiki.cosmoteer.net/"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/Cosmoteer"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/CosmoteerGame"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/cosmoteer"))
	LOCATION_X(TWITCH  , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Cosmoteer"))
)
GAME_X("The Last Leviathan", NULL, NULL,
	LOCATION_X(STEAM       , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/489460/The_Last_Leviathan/"))
	LOCATION_X(HUMBLE_STORE, RESOURCE_X(0, NULL, "https://www.humblebundle.com/store/the-last-leviathan"))
	LOCATION_X(REDDIT      , RESOURCE_X(0, NULL, "https://reddit.com/r/TheLastLeviathan/"))
	LOCATION_X(TWITTER     , RESOURCE_X(0, NULL, "https://twitter.com/The_Last_Levi"))
	LOCATION_X(INDIE_DB    , RESOURCE_X(0, NULL, "https://www.indiedb.com/games/thelastleviathan"))
	LOCATION_X(TWITCH      , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/The%20Last%20Leviathan"))
)
GAME_X("Automation - The Car Company Tycoon Game", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/293760/Automation__The_Car_Company_Tycoon_Game/"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.automationgame.com/"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCJUL2wARlIq46rUwdZG_XpQ"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/AutomationGame"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/AutomationGame"))
	LOCATION_X(FORUM   , RESOURCE_X(0, NULL, "http://discourse.automationgame.com/"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://automation.gamepedia.com/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/automationgame/"))
	LOCATION_X(TWITCH  , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Automation"))
)
GAME_X("BeamNG.drive", "actually requires third-party software to create vehicles",
	INDENT "As BeamNG.drive requires third-party programs to create new cars and other vehicles, I'm stretching the meaning of vehicle building games to include potentially any game with modding capabilities, since the creation of vehicle assets naturally occurs in the process."
	INDENT "I'll leave it here for now, since the game and its community revolves around creating new vehicles."
	,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/284160/BeamNGdrive/"))
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "https://www.beamng.com/"))
	LOCATION_X(FORUM    , RESOURCE_X(0, NULL, "https://www.beamng.com/forums/"))
	LOCATION_X(FACEBOOK , RESOURCE_X(0, NULL, "https://www.facebook.com/BeamNGPhysics"))
	LOCATION_X(TWITTER  , RESOURCE_X(0, NULL, "https://twitter.com/beamng"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCja6Jq-X1I_GnRChgWqwZBg"))
	LOCATION_X(INSTAGRAM, RESOURCE_X(0, NULL, "https://www.instagram.com/beamng.official/"))
	LOCATION_X(GITHUB   , RESOURCE_X(0, NULL, "https://github.com/BeamNG/"))
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/BeamNG/"))
	LOCATION_X(DISCORD  , RESOURCE_X(0, NULL, "https://discord.com/invite/YKcSWAy"))
	LOCATION_X(TWITCH   , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Beamng.drive"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/BeamNG.drive"))
)
GAME_X("Robot Arena", NULL, NULL,
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Robot_Arena"))
)
GAME_X("Robot Arena 2: Design and Destroy", NULL, NULL,
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Robot_Arena"))
)
GAME_X("Robot Arena 3", NULL, NULL,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/363530/Robot_Arena_III/"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Robot_Arena"))
)
GAME_X("Fraxy", NULL, NULL,
	LOCATION_X(SITE     ,
		RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20200129130946/http://monz.sp.land.to/wp/fraxy/")
		RESOURCE_X(0      , NULL, "http://fraxyhq.net/")
	)
	LOCATION_X(WIKI     ,
		RESOURCE_X(0      , NULL, "https://shmup.fandom.com/wiki/Fraxy")
		RESOURCE_X(0      , NULL, "https://tig.fandom.com/wiki/Fraxy")
		RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20100310233900/http://fraxy.kafuka.org/wiki/Main_Page")
		RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20141218150554/http://wiki.fraxy.net/index.php?title=Main_Page")
		RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20090317233751/http://fraxycompendium.pbwiki.com/")
		RESOURCE_X(0      , NULL, "http://fraxyacademy.pbworks.com/w/page/8284158/FrontPage")
		RESOURCE_X(0      , NULL, "http://fraxy.pbworks.com/w/page/8284047/The%20Bosses")
	)
	LOCATION_X(FORUM    ,
		RESOURCE_X(0      , NULL, "http://fraxyhq.net/forums/index.php")
		RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20180911174817/http://acmlm.kafuka.org/board/forum.php?id=51")
		RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20120313164954/http://fraxy.forumi.biz/")
		RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20121107142027/http://fraxyhq.com:80/forums/index.php")
	)
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/results?search_query=%22fraxy%22"))
	LOCATION_X(TV_TROPES, RESOURCE_X(0, NULL, "https://tvtropes.org/pmwiki/pmwiki.php/VideoGame/Fraxy"))
)
GAME_X("Planet Explorers", NULL, NULL,
	LOCATION_X(STEAM      , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/237870/Planet_Explorers/"))
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "http://planetexplorers.pathea.net/"))
	LOCATION_X(WIKI       ,
		RESOURCE_X(0, NULL, "https://planetexplorers.gamepedia.com/")
		RESOURCE_X(0, NULL, "https://planet-explorers.fandom.com")
	)
	LOCATION_X(KICKSTARTER, RESOURCE_X(0, NULL, "https://www.kickstarter.com/projects/1757963851/planet-explorers/"))
	LOCATION_X(WIKIPEDIA  , RESOURCE_X(0, NULL, "https://en.wikipedia.org/wiki/Planet_Explorers"))
	LOCATION_X(REDDIT     , RESOURCE_X(0, NULL, "https://reddit.com/r/PlanetExplorers/"))
	LOCATION_X(YOUTUBE    , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCtq8Yt4eS0INqlmn8sQ71oQ"))
)
GAME_X("Street rod 3", NULL, NULL,
	LOCATION_X(SITE       , RESOURCE_X(0, NULL, "http://www.streetrod3.com/"))
	LOCATION_X(FORUM      , RESOURCE_X(0, NULL, "http://forums.streetrod3.com/"))
	LOCATION_X(FREENODE   , RESOURCE_X(0, NULL, "http://www.streetrod3.com/?q=chat"))
	LOCATION_X(SOURCEFORGE, RESOURCE_X(0, NULL, "https://sourceforge.net/projects/streetrod3/"))
)
GAME_X("Brick Rigs", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/552100/Brick_Rigs/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/brickrigs"))
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/BrickRigs/"))
	LOCATION_X(WIKI   , RESOURCE_X(0, NULL, "https://brickrigs.fandom.com/"))
)
GAME_X("Lego Racers", NULL, NULL,
	LOCATION_X(MY_ABANDONWARE, RESOURCE_X(0, NULL, "https://www.myabandonware.com/game/lego-racers-bak"))
	LOCATION_X(WIKIPEDIA     , RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Lego_Racers_(video_game)"))
	LOCATION_X(YOUTUBE       , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCPkM97oIAhfo0VB1O38ZKUA"))
)
GAME_X("Lego Racers 2", NULL, NULL,
	LOCATION_X(MY_ABANDONWARE, RESOURCE_X(0, NULL, "https://www.myabandonware.com/game/lego-racers-2-bcp"))
	LOCATION_X(WIKIPEDIA     , RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Lego_Racers_2"))
	LOCATION_X(YOUTUBE       , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UC3KTAvt4i4BtG6_LccQ9rkg"))
)
GAME_X("SteamCraft", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://steamcommunity.com/sharedfiles/filedetails/?id=619286876"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/SteamCraftGame"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/SteamCraft/"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/steamcraft"))
)
GAME_X("Bad Piggies", NULL, NULL,
	LOCATION_X(CRAZY_GAMES  , RESOURCE_X(0, NULL     , "http://www.crazygames.com/game/bad-piggies"))
	LOCATION_X(PLAY_STORE   , RESOURCE_X(0, NULL     , "https://play.google.com/store/apps/details?id=com.rovio.BadPiggies"))
	LOCATION_X(APP_STORE    ,
		RESOURCE_X(0, NULL     , "https://apps.apple.com/app/bad-piggies/id533451786")
		RESOURCE_X(0, NULL     , "https://apps.apple.com/app/bad-piggies-hd/id545229893")
	)
	LOCATION_X(WINDOWS_STORE, RESOURCE_X(0, NULL, "https://www.microsoft.com/p/badpiggies/9nblggh188vg"))
	LOCATION_X(AMAZON       ,
		RESOURCE_X(0, "free"   , "https://www.amazon.com/Rovio-Entertainment-Corporation-Piggies-Free/dp/B009HQ9UHC/")
		RESOURCE_X(0, "premium", "https://www.amazon.com/Rovio-Entertainment-Corporation-Piggies-Premium/dp/B009G1J62C")
	)
	LOCATION_X(YOUTUBE      , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UC8PVyx5LBSQkJqMTyebCthw"))
	LOCATION_X(WIKIPEDIA    , RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Bad_Piggies"))
	LOCATION_X(REDDIT       , RESOURCE_X(0, NULL, "https://old.reddit.com/r/badpiggies/"))
	LOCATION_X(FACEBOOK     , RESOURCE_X(0, NULL, "https://www.facebook.com/badpiggies/"))
	LOCATION_X(TWITTER      , RESOURCE_X(0, NULL, "https://twitter.com/BadPiggies"))
	LOCATION_X(TUMBLR       , RESOURCE_X(0, NULL, "https://badpiggies.tumblr.com/"))
)
GAME_X("Airmen", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/647740/Airmen/"))
	LOCATION_X(TWITTER, RESOURCE_X(0, NULL, "https://twitter.com/AirborneGames"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/airmen"))
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/Airmen/"))
)
GAME_X("Blocky Cars Online", NULL, NULL,
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/id912968781"))
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.blockycars.online"))
	LOCATION_X(AMAZON    , RESOURCE_X(0, NULL, "https://www.amazon.com/Blocky-Cars-Online-Shooting-Games/dp/B07TXQYH7D/"))
)
GAME_X("RoverCraft", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.mobirate.rovercraft.gplay"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/rovercraft-racing/id881330346"))
	LOCATION_X(YOUTUBE   , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCPcz4Lhv0jTW_TiJkj8aQHw"))
	LOCATION_X(REDDIT    ,
		RESOURCE_X(0, NULL, "https://reddit.com/r/RoverCraft/")
		RESOURCE_X(0, NULL, "https://reddit.com/r/Rovercraft_official/")
	)
)
GAME_X("Rovercraft 2", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.mobirate.rcr2.gplay"))
)
GAME_X("C.A.T.S.", NULL, NULL,
	LOCATION_X(SITE      ,
		RESOURCE_X(0, NULL, "https://www.zeptolab.com/games/cats")
		RESOURCE_X(0, NULL, "https://www.catsthegame.com/")
	)
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/id1208561922"))
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.zeptolab.cats.google"))
	LOCATION_X(FACEBOOK  , RESOURCE_X(0, NULL, "https://www.facebook.com/catsthegame"))
	LOCATION_X(TWITTER   , RESOURCE_X(0, NULL, "https://twitter.com/catsthegame"))
	LOCATION_X(YOUTUBE   , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCnRfPIEbCTMrXUcMHEf6BAg"))
	LOCATION_X(INSTAGRAM , RESOURCE_X(0, NULL, "https://www.instagram.com/cats_the_game/"))
	LOCATION_X(FORUM     , RESOURCE_X(0, NULL, "https://forum.catsthegame.com/"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/catsthegame/"))
	LOCATION_X(DISCORD   , RESOURCE_X(0, NULL, "https://discord.com/invite/SRsgYJn"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://catsthegame.fandom.com/"))
)
GAME_X("Evolution of Species", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.EvolutionOfGames.EvolutionOfSpecies"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/evolution-of-species/id1208250929"))
)
GAME_X("Evolution of Species 2", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.EvolutionOfGames.EvolutionOfSpecies2"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/evolution-of-species-2/id1491718246"))
)
GAME_X("Hovercraft: Build Fly Retry", NULL, NULL,
	LOCATION_X(PLAY_STORE     , RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.highscorehero.hovercraft"))
	LOCATION_X(APP_STORE      , RESOURCE_X(0, NULL, "https://apps.apple.com/us/app/hovercraft-build-fly-retry/id962144693"))
	LOCATION_X(AMAZON         , RESOURCE_X(0, NULL, "https://www.amazon.com/High-Score-Hero-LLC-Hovercraft/dp/B00VPLORXE"))
	LOCATION_X(SITE           , RESOURCE_X(0, NULL, "http://www.highscorehero.com/hovercraft-press.html"))
	LOCATION_X(MICROSOFT_STORE, RESOURCE_X(0, NULL, "https://www.microsoft.com/p/hovercraft-build-fly-retry/9mwlkvbxh60m/"))
)
GAME_X("Hovercraft: Takedown", NULL, NULL,
	LOCATION_X(PLAY_STORE     , RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.highscorehero.takedown"))
	LOCATION_X(APP_STORE      , RESOURCE_X(0, NULL, "https://apps.apple.com/us/app/hovercraft-takedown-custom/id1081221532"))
	LOCATION_X(AMAZON         , RESOURCE_X(0, NULL, "https://www.amazon.com/gp/product/B01EO1PGMM/"))
	LOCATION_X(SITE           , RESOURCE_X(0, NULL, "http://www.highscorehero.com/hovercraft-takedown-press.html"))
	LOCATION_X(MICROSOFT_STORE, RESOURCE_X(0, NULL, "https://www.microsoft.com/p/hovercraft-takedown/9pkzczhwqx14"))
)
GAME_X("Hovercraft: Battle Arena", NULL, NULL,
	LOCATION_X(APP_STORE      , RESOURCE_X(0, NULL, "https://apps.apple.com/us/app/hovercraft-battle-arena/id1365265774?ls=1"))
	LOCATION_X(SITE           , RESOURCE_X(0, NULL, "http://www.highscorehero.com/hovercraft-battle-arena-press.html"))
	LOCATION_X(PLAY_STORE     , RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.highscorehero.battlearena"))
	LOCATION_X(AMAZON         , RESOURCE_X(0, NULL, "https://www.amazon.com/gp/product/B07GY13Q68/"))
	LOCATION_X(MICROSOFT_STORE, RESOURCE_X(0, NULL, "https://www.microsoft.com/p/hovercraft-battle-arena/9p5z1p6mg7cs"))
)
GAME_X("Hovercraft: Getaway", NULL, NULL,
	LOCATION_X(APP_STORE      , RESOURCE_X(0, NULL, "https://apps.apple.com/us/app/hovercraft-getaway/id1470330342"))
	LOCATION_X(PLAY_STORE     , RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.highscorehero.getaway"))
	LOCATION_X(AMAZON         , RESOURCE_X(0, NULL, "https://www.amazon.com/gp/product/B07V8LP8KM/"))
	LOCATION_X(SITE           , RESOURCE_X(0, NULL, "http://www.highscorehero.com/hovercraft-getaway-press.html"))
	LOCATION_X(MICROSOFT_STORE, RESOURCE_X(0, NULL, "https://www.microsoft.com/p/hovercraft-getaway/9p2p7h84n293"))
)
GAME_X("Trailmakers", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/585420/Trailmakers/"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/PlayTrailmakers/"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/PlayTrailmakers"))
	LOCATION_X(TWITCH  , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Trailmakers"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/Trailmakers"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.playtrailmakers.com/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/trailmakers/"))
)
GAME_X("Rift Frigate", NULL, NULL,
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "https://riftfrigate.com/"))
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/1084580/Rift_Frigate/"))
	LOCATION_X(DISCORD  , RESOURCE_X(0, NULL, "https://discord.com/invite/HSHQeG"))
	LOCATION_X(FACEBOOK , RESOURCE_X(0, NULL, "https://www.facebook.com/RiftFrigate/"))
	LOCATION_X(TWITTER  , RESOURCE_X(0, NULL, "https://twitter.com/RiftFrigate"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCo683xc3ouqgCulBoLMcXFw"))
	LOCATION_X(INSTAGRAM, RESOURCE_X(0, NULL, "https://www.instagram.com/riftfrigate/"))
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/RiftFrigate/"))
)
GAME_X("Vroomist", NULL, NULL,
	LOCATION_X(STEAM ,
		RESOURCE_X(0, NULL, "https://store.steampowered.com/app/464690/Vroomist/")
		RESOURCE_X(0, NULL, "https://steamcommunity.com/sharedfiles/filedetails/?id=657729030")
	)
	LOCATION_X(MOD_DB, RESOURCE_X(0, NULL, "https://www.moddb.com/games/vroomist"))
)
GAME_X("Draw Car 3D", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.GameFactory.DrawCar"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/draw-car-3d/id1478507005"))
)
GAME_X("Car Drawing Game", NULL, NULL,
	LOCATION_X(ITCH_IO    , RESOURCE_X(0, NULL, "https://modularmindset.itch.io/cardrawinggame"))
	LOCATION_X(PLAY_STORE ,
		RESOURCE_X(0, "original" , "https://play.google.com/store/apps/details?id=com.MathiasGeisler.CarDrawingGame")
		RESOURCE_X(0, "knockoff?", "https://play.google.com/store/apps/details?id=com.MathiasGeisler.CarDrawingGame")
	)
	LOCATION_X(CRAZY_GAMES, RESOURCE_X(0, NULL, "https://www.crazygames.com/game/car-drawing"))
	LOCATION_X(YOUTUBE    , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCrATFQ4VEPpUGGPQUlZTMng"))
	LOCATION_X(TWITTER    , RESOURCE_X(0, NULL, "https://twitter.com/CarDrawingGame"))
)
GAME_X("Draw Joust!", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=ru.galya.drawjoust"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/draw-joust/id1497532365"))
)
GAME_X("Rugged Rovers", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0      , NULL, "https://play.google.com/store/apps/details?id=com.preloaded.RuggedRovers"))
	LOCATION_X(APP_STORE , RESOURCE_X(0      , NULL, "https://apps.apple.com/app/rugged-rovers/id945717780"))
	LOCATION_X(SITE      , RESOURCE_X(ARCHIVE, NULL, "https://webarchive.nationalarchives.gov.uk/20170202172025/http://www.sciencemuseum.org.uk/online_science/games/rugged-rovers"))
)
GAME_X("Robotics!", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.zeptolab.robotics"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/id1476051009"))
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://www.zeptolab.com/games/robotics"))
)
GAME_X("Solaris: Rover Expedition", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=co.uk.fanstudio.solaris"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/solaris-rover-expedition/id982969463"))
)
GAME_X("Block Tech Sandbox", "aka Block Tech: Epic Sandbox or Block Tech: Epic Sandbox Craft Simulator Online", NULL,
	LOCATION_X(PLAY_STORE  ,
		RESOURCE_X(0, "free", "https://play.google.com/store/apps/details?id=com.NGG.BlockTech")
		RESOURCE_X(0, "gold", "https://play.google.com/store/apps/details?id=com.NGG.BlockTech")
	)
	LOCATION_X(APP_STORE   , RESOURCE_X(0, NULL, "https://apps.apple.com/app/block-tech-sandbox-online/id1465592382"))
	LOCATION_X(CRAZY_GAMES , RESOURCE_X(0, NULL, "https://www.crazygames.com/game/block-tech-epic-sandbox"))
	LOCATION_X(SILVER_GAMES, RESOURCE_X(0, NULL, "https://www.silvergames.com/block-tech-epic-sandbox"))
)
GAME_X("boxz.io", NULL, NULL,
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://boxz.io/"))
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.mawika.boxzio"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/boxz-io/id1399858006"))
	LOCATION_X(ITCH_IO   , RESOURCE_X(0, NULL, "https://mawika.itch.io/boxzio"))
)
GAME_X("Car Builder and Racing Game for Kids", "aka Racing Car Game for Kids 3 - 6", NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.pizzagames.constructcar"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/racing-car-game-for-kids-3-6/id1210523882"))
)
GAME_X("Evercraft Mechanic: Online Sandbox from Scrap", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.craft.scrap"))
	LOCATION_X(YOUTUBE   , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UC2YFY3veqrsCDV2PGyMeugQ"))
)
GAME_X("Evertech Sandbox", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.evertechsandbox"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/evertech-sandbox/id1422791215"))
	LOCATION_X(ITCH_IO   , RESOURCE_X(0, NULL, "https://vitsum.itch.io/evertech-sandbox"))
	LOCATION_X(SITE      ,
		RESOURCE_X(0, NULL, "http://evertechsandbox.com/")
		RESOURCE_X(0, NULL, "http://vitsum.ml/")
	)
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://evertechsandbox.gamepedia.com"))
)
GAME_X("Spaceflight Simulator", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.StefMorojna.SpaceflightSimulator"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apple.com/us/app/spaceflight-simulator/id1308057272"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/SpaceflightSimulator/"))
	LOCATION_X(DISCORD   , RESOURCE_X(0, NULL, "https://discord.com/invite/WeWxYfg"))
	LOCATION_X(FORUM     , RESOURCE_X(0, NULL, "https://jmnet.one/sfs/forum/"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://spaceflight-simulator.fandom.com/"))
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "http://spaceflight-simulator.webflow.io/"))
)
GAME_X("Super Tank Rumble", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.stove.supertank.google"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/super-tank-rumble/id1124294145"))
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://page.onstove.com/supertank/global"))
	LOCATION_X(FACEBOOK  , RESOURCE_X(0, NULL, "https://www.facebook.com/SuperTankRumble.KOR/"))
)
GAME_X("Super Tank Blitz", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.smilegate.supertankblitz.stove.google"))
	LOCATION_X(APP_STORE , RESOURCE_X(0, NULL, "https://apps.apple.com/app/supertankblitz/id1498749042"))
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "https://page.onstove.com/supertankblitz/"))
	LOCATION_X(YOUTUBE   , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UC4K4pwXr5bMphPUgbJ5kghA"))
)
GAME_X("World of Microbes", NULL, NULL,
	LOCATION_X(PLAY_STORE, RESOURCE_X(0, NULL, "https://play.google.com/store/apps/details?id=com.rexground.microbes"))
)
GAME_X("Fantastic Contraption", NULL, NULL,
	LOCATION_X(SITE           , RESOURCE_X(0, NULL, "http://www.fantasticcontraption.com/original/"))
	LOCATION_X(KONGREGATE     , RESOURCE_X(0, NULL, "https://www.kongregate.com/games/inXile_Ent/fantastic-contraption"))
	LOCATION_X(ADDICTING_GAMES, RESOURCE_X(0, NULL, "https://www.addictinggames.com/action/fantastic-contraption"))
	LOCATION_X(ARMOR_GAMES    , RESOURCE_X(0, NULL, "https://armorgames.com/play/4920/fantastic-contraption"))
	LOCATION_X(NEWGROUNDS     , RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/518732"))
	LOCATION_X(CRAZY_GAMES    , RESOURCE_X(0, NULL, "https://www.crazygames.com/game/fantastic-contraption"))
	LOCATION_X(FLONGA         , RESOURCE_X(0, NULL, "http://www.flonga.com/play/fantastic-contraption.htm"))
	LOCATION_X(NOT_DOPPLER    , RESOURCE_X(0, NULL, "http://www.notdoppler.com/fantasticcontraption.php"))
	LOCATION_X(BUBBLEBOX      , RESOURCE_X(0, NULL, "https://www.bubblebox.com/play/1148/fantastic-contraption.htm"))
	LOCATION_X(REDDIT         , RESOURCE_X(0, NULL, "https://reddit.com/r/FantasticContraption/"))
	LOCATION_X(STEAM          , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/1363690/Fantastic_Contraption_Classic_1__2/"))
)
GAME_X("Fantastic Contraption Prius Edition", NULL, NULL,
	LOCATION_X(KONGREGATE, RESOURCE_X(0, NULL, "https://www.kongregate.com/games/inxile_ent/fantastic-contraption-prius-edition"))
	LOCATION_X(FLONGA    , RESOURCE_X(0, NULL, "http://www.flonga.com/play/fantastic-contraption-prius.htm"))
	LOCATION_X(JAYISGAMES, RESOURCE_X(0, NULL, "https://jayisgames.com/review/fantastic-contraption-prius-edition.php"))
)
GAME_X("Fantastic Contraption 2", NULL, NULL,
	LOCATION_X(KONGREGATE, RESOURCE_X(0, NULL, "https://www.kongregate.com/games/sparkworkz/fantastic-contraption-2"))
	LOCATION_X(NEWGROUNDS, RESOURCE_X(0, NULL, "https://www.newgrounds.com/portal/view/549651"))
	LOCATION_X(BUBBLEBOX , RESOURCE_X(0, NULL, "https://www.bubblebox.com/play/1908/fantastic-contraption-2.htm"))
	LOCATION_X(FLONGA    , RESOURCE_X(0, NULL, "http://www.flonga.com/play/fantastic-contraption-2.htm"))
	LOCATION_X(STEAM     , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/1363690/Fantastic_Contraption_Classic_1__2/"))
)
GAME_X("Fantastic Contraption", "the new one for VR", NULL,
	LOCATION_X(STEAM            , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/386690/Fantastic_Contraption/"))
	LOCATION_X(OCULUS_STORE     , RESOURCE_X(0, NULL, "https://www.oculus.com/experiences/rift/922076897882360/"))
	LOCATION_X(PLAYSTATION_STORE, RESOURCE_X(0, NULL, "https://store.playstation.com/en-us/product/UP0551-CUSA07387_00-FCNA000000000001"))
	LOCATION_X(WINDOWS_STORE    , RESOURCE_X(0, NULL, "https://www.microsoft.com/p/fantastic-contraption/"))
	LOCATION_X(SITE             , RESOURCE_X(0, NULL, "http://www.fantasticcontraption.com/"))
	LOCATION_X(DISCORD          , RESOURCE_X(0, NULL, "https://discord.com/invite/mW5rNQd"))
	LOCATION_X(PATREON          , RESOURCE_X(0, NULL, "https://www.patreon.com/FantasticContraption"))
	LOCATION_X(YOUTUBE          , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCabhR4YEQEnmHTqBCxTU5qg"))
	LOCATION_X(WIKIPEDIA        , RESOURCE_X(0, NULL, "https://en.wikipedia.org/wiki/Fantastic_Contraption_(2016_video_game)"))
)
GAME_X("Pixel Piracy", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/264140/Pixel_Piracy/"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UC0NRY49LuLfILInnY04yang"))
	LOCATION_X(TWITTER, RESOURCE_X(0, NULL, "https://twitter.com/PixelPiracyGame"))
)
GAME_X("Raft", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/648800/Raft/"))
	LOCATION_X(ITCH_IO , RESOURCE_X(0, NULL, "https://raft.itch.io/raft"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/raft"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/RaftSurvivaGame"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.raft-game.com/"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/RaftGame/"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://raft.gamepedia.com/"))
	LOCATION_X(REDDIT  ,
		RESOURCE_X(0, NULL, "https://reddit.com/r/RaftTheGame/")
		RESOURCE_X(0, NULL, "https://reddit.com/r/raft/")
	)
	LOCATION_X(FORUM   , RESOURCE_X(0, NULL, "https://steamcommunity.com/app/648800/discussions/"))
)
GAME_X("Space Engineers", NULL, NULL,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/244850/Space_Engineers/"))
	LOCATION_X(XBOX     , RESOURCE_X(0, NULL, "https://www.microsoft.com/p/space-engineers-ultimate-edition-2019/9pmh67g2bxkr"))
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/spaceengineers/"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCXlRk5ebt5HcAVtd_4ft22Q"))
	LOCATION_X(FACEBOOK , RESOURCE_X(0, NULL, "https://www.facebook.com/SpaceEngineers"))
	LOCATION_X(TWITTER  , RESOURCE_X(0, NULL, "https://twitter.com/SpaceEngineersG"))
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "https://www.spaceengineersgame.com/"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Space_Engineers"))
)
GAME_X("Masterspace", NULL, NULL,
	LOCATION_X(STEAM, RESOURCE_X(0      , NULL, "http://store.steampowered.com/app/282860"))
	LOCATION_X(SITE , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20160324203225/http://www.master-space.com/"))
	LOCATION_X(FORUM, RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20160328112542/http://master-space.com/forum/"))
	LOCATION_X(WIKI , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20160229033953/http://www.master-space.com/wiki/index.php/Main_Page"))
)
GAME_X("Main Assembly", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/1078920/Main_Assembly/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/Vw73KKh"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/MainAssembly/"))
	LOCATION_X(MOD_DB  , RESOURCE_X(0, NULL, "https://www.moddb.com/games/main-assembly"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/main-assembly"))
)
GAME_X("Mechanic Miner", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/745010/Mechanic_Miner/"))
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.mechanicminer.com/"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/mechanic_miner"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/uQxFyzs"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/mechanicminer/"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://mechanicminer.gamepedia.com/"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCYrR5YnLzOe71bwOCNX-FDA"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/MechanicMiner/"))
	LOCATION_X(INDIE_DB, RESOURCE_X(0, NULL, "https://www.indiedb.com/games/mechanic-miner/"))
	LOCATION_X(MOD_DB  , RESOURCE_X(0, NULL, "https://www.moddb.com/games/mechanic-miner"))
)
GAME_X("Starship Theory", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/574760/Starship_Theory/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/StarshipTheory/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/yJzQpt6"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/starshiptheory/"))
	LOCATION_X(TWITCH  , RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Starship%20Theory"))
)
GAME_X("Blockade Runner", NULL, NULL,
	LOCATION_X(INDIE_DB, RESOURCE_X(0      , NULL, "https://www.indiedb.com/games/blockade-runner"))
	LOCATION_X(STEAM   , RESOURCE_X(0      , NULL, "https://steamcommunity.com/sharedfiles/filedetails/?id=92997153"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0      , NULL, "https://www.facebook.com/BlockadeRunnerGame/"))
	LOCATION_X(SITE    , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20160928195813/http://blockaderunnergame.com:80/"))
	LOCATION_X(FORUM   , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20160920114751/http://forums.blockaderunnergame.com/"))
	LOCATION_X(QUAKENET, RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20160920114746/http://forums.blockaderunnergame.com/index.php?topic=2398.0"))
)
GAME_X("Shores of Hazeron", NULL, NULL,
	LOCATION_X(SITE    , RESOURCE_X(0, NULL, "https://www.hazeron.com/"))
	LOCATION_X(WIKI    , RESOURCE_X(0, NULL, "https://www.hazeron.com/wiki/"))
	LOCATION_X(FORUM   , RESOURCE_X(0, NULL, "https://www.hazeron.com/mybb/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/Shores_of_Hazeron/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/CPrpDzJ"))
	LOCATION_X(YOUTUBE , RESOURCE_X(0, NULL, "https://www.youtube.com/results?search_query=%22Shores+of+Hazeron%22"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/Hazeron"))
)
GAME_X("BREAK ARTS II", NULL, NULL,
	LOCATION_X(STEAM , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/547360/BREAK_ARTS_II/"))
	LOCATION_X(SITE  , RESOURCE_X(0, NULL, "http://publishing.playism-games.com/break-arts-II"))
	LOCATION_X(TWITCH, RESOURCE_X(0, NULL, "https://www.twitch.tv/directory/game/Break%20Arts%20II"))
)
GAME_X("RoboCo", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/1067220/RoboCo/"))
	LOCATION_X(REDDIT , RESOURCE_X(0, NULL, "https://reddit.com/r/roboco/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/pYTHrt2"))
	LOCATION_X(TWITTER, RESOURCE_X(0, NULL, "https://twitter.com/RoboCoGame"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCCzDbC5wmLT28omYT6llSXg/"))
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "https://roboco.co/"))
)
GAME_X("Stormworks: Build and Rescue", NULL, NULL,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/573090/Stormworks_Build_and_Rescue/"))
	LOCATION_X(DISCORD  , RESOURCE_X(0, NULL, "https://discord.com/invite/stormworks"))
	LOCATION_X(REDDIT   , RESOURCE_X(0, NULL, "https://reddit.com/r/Stormworks/"))
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "http://mcro.org/stormworks"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://wikipedia.org/wiki/Stormworks:_Build_and_Rescue"))
)
GAME_X("Cargo! The Quest for Gravity", NULL, NULL,
	LOCATION_X(STEAM    , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/41740/Cargo_The_Quest_for_Gravity/"))
	LOCATION_X(TV_TROPES, RESOURCE_X(0, NULL, "https://tvtropes.org/pmwiki/pmwiki.php/VideoGame/CargoTheQuestForGravity"))
)
GAME_X("Sea of Craft", NULL, NULL,
	LOCATION_X(STEAM   , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/990920/_Sea_of_Craft/"))
	LOCATION_X(DISCORD , RESOURCE_X(0, NULL, "https://discord.com/invite/tXyhYTb"))
	LOCATION_X(TWITTER , RESOURCE_X(0, NULL, "https://twitter.com/seaofcraft"))
	LOCATION_X(FACEBOOK, RESOURCE_X(0, NULL, "https://www.facebook.com/Seaofcraft/"))
	LOCATION_X(REDDIT  , RESOURCE_X(0, NULL, "https://reddit.com/r/seaofcraft/"))
)
GAME_X("Space Run", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/275670/Space_Run/"))
	LOCATION_X(YOUTUBE, RESOURCE_X(0, NULL, "https://www.youtube.com/channel/UCQacaaSO5jtTSTNSmS2sblA"))
)
GAME_X("Space Run Galaxy", NULL, NULL,
	LOCATION_X(STEAM, RESOURCE_X(0, NULL, "https://store.steampowered.com/app/355800/Space_Run_Galaxy/"))
)
GAME_X("Captain Forever", NULL, NULL,
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "http://www.captainforever.com/captainforever.php"))
	LOCATION_X(FORUM     ,
		RESOURCE_X(0, NULL, "https://cptforever.proboards.com/")
		RESOURCE_X(0, NULL, "https://forums.tigsource.com/index.php?topic=8095.0")
	)
	LOCATION_X(DISCORD   , RESOURCE_X(0, NULL, "https://discord.com/invite/xFzwTZU"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://captainforever.fandom.com/"))
	LOCATION_X(CONTENT   , RESOURCE_X(0, NULL, "https://vcd.phuce.com/"))
	LOCATION_X(JAYISGAMES, RESOURCE_X(0, NULL, "https://jayisgames.com/review/captain-forever.php"))
	LOCATION_X(TWITTER   , RESOURCE_X(0, NULL, "https://twitter.com/CaptainForever"))
	LOCATION_X(WIKIPEDIA , RESOURCE_X(0, NULL, "https://en.wikipedia.org/wiki/Captain_Forever"))
	LOCATION_X(TV_TROPES , RESOURCE_X(0, NULL, "https://tvtropes.org/pmwiki/pmwiki.php/VideoGame/CaptainForever"))
	LOCATION_X(REDDIT    , RESOURCE_X(0, NULL, "https://reddit.com/r/captainforever/new/"))
)
GAME_X("Captain Successor", NULL, NULL,
	LOCATION_X(SITE      , RESOURCE_X(0, NULL, "http://www.captainforever.com/captainsuccessor.php"))
	LOCATION_X(FORUM     , RESOURCE_X(0, NULL, "https://cptforever.proboards.com/board/12/captain-successor"))
	LOCATION_X(WIKI      , RESOURCE_X(0, NULL, "https://captainforever.fandom.com/wiki/Captain_Successor"))
	LOCATION_X(DISCORD   , RESOURCE_X(0, NULL, "https://discord.com/invite/xFzwTZU"))
	LOCATION_X(JAYISGAMES, RESOURCE_X(0, NULL, "https://jayisgames.com/review/captain-forever.php"))
)
GAME_X("The Down Star", "aka Captain Jameson", NULL,
	LOCATION_X(SITE   , RESOURCE_X(0, NULL, "http://www.captainforever.com/thedawnstar.php"))
	LOCATION_X(FORUM  , RESOURCE_X(0, NULL, "https://cptforever.proboards.com/board/11/dawn-star-captain-jameson-alpha"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/xFzwTZU"))
	LOCATION_X(WIKI   , RESOURCE_X(0, NULL, "https://captainforever.fandom.com/wiki/Captain_Jameson"))
)
GAME_X("Captain Forever Trilogy", NULL, NULL,
	LOCATION_X(STEAM  , RESOURCE_X(0, NULL, "https://store.steampowered.com/app/758930/Captain_Forever_Trilogy/"))
	LOCATION_X(DISCORD, RESOURCE_X(0, NULL, "https://discord.com/invite/xFzwTZU"))
)
GAME_X("Captain Forever Remix", NULL, NULL,
	LOCATION_X(STEAM       , RESOURCE_X(0      , NULL, "https://store.steampowered.com/app/298560/Captain_Forever_Remix/"))
	LOCATION_X(HUMBLE_STORE, RESOURCE_X(0      , NULL, "https://www.humblebundle.com/store/captain-forever-remix"))
	LOCATION_X(ITCH_IO     , RESOURCE_X(0      , NULL, "https://pixelsaurusgames.itch.io/captain-forever-remix"))
	LOCATION_X(SITE        , RESOURCE_X(ARCHIVE, NULL, "https://web.archive.org/web/20190103111425/http://captainforeverremix.com/"))
	LOCATION_X(FACEBOOK    , RESOURCE_X(0      , NULL, "https://www.facebook.com/captainforeverremix"))
	LOCATION_X(TWITTER     , RESOURCE_X(0      , NULL, "https://twitter.com/CapForeverRemix"))
	LOCATION_X(YOUTUBE     , RESOURCE_X(0      , NULL, "https://www.youtube.com/results?search_query=%22captain+forever+remix%22"))
	LOCATION_X(TWITCH      , RESOURCE_X(0      , NULL, "https://www.twitch.tv/directory/game/Captain%20Forever%20Remix"))
)
GAME_X("Battleships Forever", NULL, NULL,
	LOCATION_X(SITE     , RESOURCE_X(0, NULL, "http://www.wyrdysm.com/games.php"))
	LOCATION_X(FORUM    , RESOURCE_X(0, NULL, "http://www.wyrdysm.com/phpBB3/index.php"))
	LOCATION_X(DISCORD  , RESOURCE_X(0, NULL, "https://discord.com/invite/Up2Tz4S"))
	LOCATION_X(YOUTUBE  , RESOURCE_X(0, NULL, "https://www.youtube.com/results?search_query=%22battleships+forever%22"))
	LOCATION_X(WIKIPEDIA, RESOURCE_X(0, NULL, "https://en.wikipedia.org/wiki/Battleships_Forever"))
	LOCATION_X(TV_TROPES, RESOURCE_X(0, NULL, "https://tvtropes.org/pmwiki/pmwiki.php/VideoGame/BattleshipsForever"))
)
GAME_X("Waste of Space", NULL, NULL,
	LOCATION_X(GITHUB, RESOURCE_X(MENTION, NULL, "https://github.com/raysan5/raylib/issues/1326#issuecomment-666333718"))
)